import groovy.transform.Field

@Field DRY_RUN = false

def getHomePages() {
    return sql2Query("""
        SELECT * FROM [nt:unstructured] AS node
        WHERE ISDESCENDANTNODE('/content/dhl')
        AND node.[cq:template] = '/conf/dhl/settings/wcm/templates/home-page'
    """).stream().map{ it.getParent() };
}

@Field DICTIONARY_SHOWCASE_PANEL = [
        "en-IE": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "de": ["Clothes Stack": "Kleider-Stapel", "Bag": "Tasche", "Recycling": "Recycling", "Piano": "Klavier", "Keys": "Tasten", "Strings": "Streichinstrumente", "Watch": "Uhr", "Beehive": "Bienenstock", "Test Tube": "Reagenzglas", "Pineapple": "Ananas", "Tree": "Baum", "Milk Tettra pack": "Milch Tettra Packung", "Pen": "Feder", "Map": "Landkarte", "Book": "Buch", "Digital patient summary board": "Digitale Patientenübersicht", "Blook test on mobile": "Blook-Test auf dem Handy", "Heart rate on smart watch": "Herzfrequenz auf der Smartwatch", "Digital Camera": "Digitalkamera", "Bulb": "Glühlampe", "Speed": "Geschwindigkeit", "Rugby": "Rugby", "Go-pro": "Auf Deutsch", "Heart in a box": "Herz in der Schachtel", "Piggybank in a box": "Sparschwein in der Schachtel", "Recycle in a box": "Recycling in einer Box", "Gift in a box": "Geschenk in einer Schachtel", "Bell": "Glocke", "Bubbles": "Blasen", "Opening case": "Öffnen des Gehäuses", "DNA": "DNS", "Speakers": "Lautsprecher", "Headphones": "Kopfhörer", "Wireless Charger": "Kabelloses Ladegerät"],
        "hi": ["Clothes Stack": "कपड़े का ढेर", "Bag": "झपट लेना", "Recycling": "पुनर्चक्रण", "Piano": "पियानो", "Keys": "कुंजियां", "Strings": "तार", "Watch": "सतर्कता", "Beehive": "मधुमक्खी का छत्ता", "Test Tube": "परखनली", "Pineapple": "अनन्‍नास", "Tree": "दरख्‍़त", "Milk Tettra pack": "दूध टेट्रा पैक", "Pen": "बाड़ा", "Map": "मानचित्र", "Book": "किताब", "Digital patient summary board": "डिजिटल रोगी सारांश बोर्ड", "Blook test on mobile": "मोबाइल पर Blook टेस्ट", "Heart rate on smart watch": "स्मार्ट घड़ी पर हृदय गति", "Digital Camera": "डिजिटल कैमरा", "Bulb": "कंद", "Speed": "गति", "Rugby": "रगबी", "Go-pro": "गो-प्रो", "Heart in a box": "एक बॉक्स में दिल", "Piggybank in a box": "एक बॉक्स में पिग्गीबैंक", "Recycle in a box": "एक बॉक्स में रीसायकल", "Gift in a box": "एक बॉक्स में उपहार", "Bell": "घंटी", "Bubbles": "बुलबुले", "Opening case": "खुलने का मामला", "DNA": "डीएनए", "Speakers": "वक्ताओं", "Headphones": "हेडफ़ोन", "Wireless Charger": "वायरलेस चार्जर"],
        "en-US": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "pt": ["Clothes Stack": "Pilha de roupas", "Bag": "Saco", "Recycling": "Reciclagem", "Piano": "Piano", "Keys": "Chaves", "Strings": "Strings", "Watch": "Relógio", "Beehive": "Colmeia", "Test Tube": "Tubo de ensaio", "Pineapple": "Abacaxi", "Tree": "Árvore", "Milk Tettra pack": "Pacote Milk Tettra", "Pen": "Caneta", "Map": "Mapa", "Book": "Livro", "Digital patient summary board": "Quadro digital de resumo do paciente", "Blook test on mobile": "Teste Blook no celular", "Heart rate on smart watch": "Frequência cardíaca no relógio inteligente", "Digital Camera": "Câmera digital", "Bulb": "Lâmpada", "Speed": "Velocidade", "Rugby": "Rúgbi", "Go-pro": "Ir pro", "Heart in a box": "Coração em uma caixa", "Piggybank in a box": "Cofrinho em uma caixa", "Recycle in a box": "Reciclar em uma caixa", "Gift in a box": "Presente em uma caixa", "Bell": "Sino", "Bubbles": "Bolhas", "Opening case": "Caixa de abertura", "DNA": "ADN", "Speakers": "Falantes", "Headphones": "Auscultadores", "Wireless Charger": "Carregador sem fio"],
        "en-MM": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-IN": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-ZA": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "hu": ["Clothes Stack": "Ruhahalom", "Bag": "Táska", "Recycling": "Újrahasznosítás", "Piano": "Zongora", "Keys": "Kulcsok", "Strings": "Vonósok", "Watch": "Néz", "Beehive": "Kaptár", "Test Tube": "Kémcső", "Pineapple": "Ananász", "Tree": "Fa", "Milk Tettra pack": "Tej Tettra csomag", "Pen": "Toll", "Map": "Térkép", "Book": "Könyv", "Digital patient summary board": "Digitális beteg-összefoglaló tábla", "Blook test on mobile": "Blook teszt mobilon", "Heart rate on smart watch": "Pulzusszám az okosórán", "Digital Camera": "Digitális fényképezőgép", "Bulb": "Villanykörte", "Speed": "Sebesség", "Rugby": "Rögbi", "Go-pro": "Profi", "Heart in a box": "Szív egy dobozban", "Piggybank in a box": "Malacka persely dobozban", "Recycle in a box": "Újrahasznosítás dobozban", "Gift in a box": "Ajándék dobozban", "Bell": "Harang", "Bubbles": "Buborékok", "Opening case": "Nyitó tok", "DNA": "DNS", "Speakers": "Hangszórók", "Headphones": "Fejhallgató", "Wireless Charger": "Vezeték nélküli töltő"],
        "nl-BE": ["Clothes Stack": "Kleding stapelen", "Bag": "Zak", "Recycling": "Recyclage", "Piano": "Piano", "Keys": "Sleutels", "Strings": "Tekenreeksen", "Watch": "Horloge", "Beehive": "Bijenkorf", "Test Tube": "Reageerbuis", "Pineapple": "Ananas", "Tree": "Boom", "Milk Tettra pack": "Melk Tettra pakket", "Pen": "Pen", "Map": "Kaart", "Book": "Boek", "Digital patient summary board": "Digitaal patiëntenoverzichtsbord", "Blook test on mobile": "Blook-test op mobiel", "Heart rate on smart watch": "Hartslag op smartwatch", "Digital Camera": "Digitale camera", "Bulb": "Gloeilamp", "Speed": "Snelheid", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Hart in een doosje", "Piggybank in a box": "Spaarvarken in een doosje", "Recycle in a box": "Recyclen in een doos", "Gift in a box": "Cadeau in een doos", "Bell": "Klok", "Bubbles": "Bellen", "Opening case": "Koffer openen", "DNA": "DNA", "Speakers": "Luidsprekers", "Headphones": "Hoofdtelefoon", "Wireless Charger": "Draadloze oplader"],
        "zh-CN": ["Clothes Stack": "衣物堆叠", "Bag": "袋", "Recycling": "回收", "Piano": "钢琴", "Keys": "钥匙", "Strings": "字符串", "Watch": "看", "Beehive": "蜂窝", "Test Tube": "试管", "Pineapple": "菠萝", "Tree": "树", "Milk Tettra pack": "Milk Tettra 包装", "Pen": "笔", "Map": "地图", "Book": "书", "Digital patient summary board": "数字患者汇总板", "Blook test on mobile": "移动端 Blook 测试", "Heart rate on smart watch": "智能手表上的心率", "Digital Camera": "数码相机", "Bulb": "灯泡", "Speed": "速度", "Rugby": "橄榄球", "Go-pro": "Go-pro 认证", "Heart in a box": "心装盒", "Piggybank in a box": "盒子里的存钱罐", "Recycle in a box": "盒中回收", "Gift in a box": "盒装礼品", "Bell": "钟", "Bubbles": "泡沫", "Opening case": "开箱", "DNA": "脱氧核糖核酸", "Speakers": "扬声器", "Headphones": "耳机", "Wireless Charger": "无线充电器"],
        "en-IT": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "el-GR": ["Clothes Stack": "Στοίβα ρούχων", "Bag": "Σακούλα", "Recycling": "Ανακύκλωση", "Piano": "Πιάνο", "Keys": "Κλειδιά", "Strings": "Συμβολοσειρές", "Watch": "Ρολόι", "Beehive": "Κυψέλη", "Test Tube": "Δοκιμαστικός σωλήνας", "Pineapple": "Ανανάς", "Tree": "Δέντρο", "Milk Tettra pack": "Πακέτο γάλακτος Tettra", "Pen": "Στυλό", "Map": "Χάρτης", "Book": "Βιβλίο", "Digital patient summary board": "Ψηφιακός πίνακας σύνοψης ασθενών", "Blook test on mobile": "Δοκιμή Blook σε κινητό", "Heart rate on smart watch": "Καρδιακός ρυθμός στο έξυπνο ρολόι", "Digital Camera": "Ψηφιακή φωτογραφική μηχανή", "Bulb": "Βολβός", "Speed": "Ταχύτητα", "Rugby": "Ράγκμπι", "Go-pro": "Πάμε-επαγγελματίας", "Heart in a box": "Καρδιά σε κουτί", "Piggybank in a box": "Κουμπαράς σε κουτί", "Recycle in a box": "Ανακύκλωση σε κουτί", "Gift in a box": "Δώρο σε κουτί", "Bell": "Κουδούνι", "Bubbles": "Φυσαλίδες", "Opening case": "Ανοιγόμενη θήκη", "DNA": "DNA", "Speakers": "Ηχεία", "Headphones": "Ακουστικά", "Wireless Charger": "Ασύρματος φορτιστής"],
        "en-MY": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-ES": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-AT": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-AU": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "id": ["Clothes Stack": "Tumpukan Pakaian", "Bag": "Tas", "Recycling": "Daur ulang", "Piano": "Piano", "Keys": "Tombol", "Strings": "String", "Watch": "Menonton", "Beehive": "Beehive", "Test Tube": "Tabung reaksi", "Pineapple": "Nanas", "Tree": "Pohon", "Milk Tettra pack": "Paket Tettra Susu", "Pen": "Pena", "Map": "Peta", "Book": "Buku", "Digital patient summary board": "Papan ringkasan pasien digital", "Blook test on mobile": "Tes Blook di ponsel", "Heart rate on smart watch": "Detak jantung pada jam tangan pintar", "Digital Camera": "Kamera Digital", "Bulb": "Bohlam", "Speed": "Kecepatan", "Rugby": "Rugby", "Go-pro": "Pergi pro", "Heart in a box": "Hati dalam kotak", "Piggybank in a box": "Celengan dalam kotak", "Recycle in a box": "Daur ulang dalam kotak", "Gift in a box": "Hadiah dalam kotak", "Bell": "Lonceng", "Bubbles": "Gelembung", "Opening case": "Kasus pembuka", "DNA": "DNA", "Speakers": "Speaker", "Headphones": "Headphone", "Wireless Charger": "Pengisi Daya Nirkabel"],
        "en-NG": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-VN": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "de-CH": ["Clothes Stack": "Kleider-Stapel", "Bag": "Tasche", "Recycling": "Recycling", "Piano": "Klavier", "Keys": "Tasten", "Strings": "Streichinstrumente", "Watch": "Uhr", "Beehive": "Bienenstock", "Test Tube": "Reagenzglas", "Pineapple": "Ananas", "Tree": "Baum", "Milk Tettra pack": "Milch Tettra Packung", "Pen": "Feder", "Map": "Landkarte", "Book": "Buch", "Digital patient summary board": "Digitale Patientenübersicht", "Blook test on mobile": "Blook-Test auf dem Handy", "Heart rate on smart watch": "Herzfrequenz auf der Smartwatch", "Digital Camera": "Digitalkamera", "Bulb": "Glühlampe", "Speed": "Geschwindigkeit", "Rugby": "Rugby", "Go-pro": "Auf Deutsch", "Heart in a box": "Herz in der Schachtel", "Piggybank in a box": "Sparschwein in der Schachtel", "Recycle in a box": "Recycling in einer Box", "Gift in a box": "Geschenk in einer Schachtel", "Bell": "Glocke", "Bubbles": "Blasen", "Opening case": "Öffnen des Gehäuses", "DNA": "DNS", "Speakers": "Lautsprecher", "Headphones": "Kopfhörer", "Wireless Charger": "Kabelloses Ladegerät"],
        "ms": ["Clothes Stack": "Timbunan Pakaian", "Bag": "Beg", "Recycling": "Kitar semula", "Piano": "Piano", "Keys": "Kekunci", "Strings": "Rentetan", "Watch": "Menonton", "Beehive": "Sarang lebah", "Test Tube": "Tabung uji", "Pineapple": "Nanas", "Tree": "Pokok", "Milk Tettra pack": "Pek Susu Tettra", "Pen": "Pen", "Map": "Peta", "Book": "Buku", "Digital patient summary board": "Papan ringkasan pesakit digital", "Blook test on mobile": "Ujian Blook pada telefon bimbit", "Heart rate on smart watch": "Kadar denyutan jantung pada jam tangan pintar", "Digital Camera": "Kamera Digital", "Bulb": "Mentol", "Speed": "Kelajuan", "Rugby": "Ragbi", "Go-pro": "Go-pro", "Heart in a box": "Hati dalam kotak", "Piggybank in a box": "Piggybank dalam kotak", "Recycle in a box": "Kitar semula dalam kotak", "Gift in a box": "Hadiah dalam kotak", "Bell": "Loceng", "Bubbles": "Buih", "Opening case": "Kes pembukaan", "DNA": "DNA", "Speakers": "Pembesar suara", "Headphones": "Fon kepala", "Wireless Charger": "Pengecas Tanpa Wayar"],
        "en-BD": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "el": ["Clothes Stack": "Στοίβα ρούχων", "Bag": "Σακούλα", "Recycling": "Ανακύκλωση", "Piano": "Πιάνο", "Keys": "Κλειδιά", "Strings": "Συμβολοσειρές", "Watch": "Ρολόι", "Beehive": "Κυψέλη", "Test Tube": "Δοκιμαστικός σωλήνας", "Pineapple": "Ανανάς", "Tree": "Δέντρο", "Milk Tettra pack": "Πακέτο γάλακτος Tettra", "Pen": "Στυλό", "Map": "Χάρτης", "Book": "Βιβλίο", "Digital patient summary board": "Ψηφιακός πίνακας σύνοψης ασθενών", "Blook test on mobile": "Δοκιμή Blook σε κινητό", "Heart rate on smart watch": "Καρδιακός ρυθμός στο έξυπνο ρολόι", "Digital Camera": "Ψηφιακή φωτογραφική μηχανή", "Bulb": "Βολβός", "Speed": "Ταχύτητα", "Rugby": "Ράγκμπι", "Go-pro": "Πάμε-επαγγελματίας", "Heart in a box": "Καρδιά σε κουτί", "Piggybank in a box": "Κουμπαράς σε κουτί", "Recycle in a box": "Ανακύκλωση σε κουτί", "Gift in a box": "Δώρο σε κουτί", "Bell": "Κουδούνι", "Bubbles": "Φυσαλίδες", "Opening case": "Ανοιγόμενη θήκη", "DNA": "DNA", "Speakers": "Ηχεία", "Headphones": "Ακουστικά", "Wireless Charger": "Ασύρματος φορτιστής"],
        "en": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "it": ["Clothes Stack": "Pila di vestiti", "Bag": "Sacco", "Recycling": "Riciclaggio", "Piano": "Pianoforte", "Keys": "Chiavi", "Strings": "Stringhe", "Watch": "Orologio", "Beehive": "Alveare", "Test Tube": "Provetta", "Pineapple": "Ananas", "Tree": "Albero", "Milk Tettra pack": "Confezione Tettra al latte", "Pen": "Penna", "Map": "Mappa", "Book": "Libro", "Digital patient summary board": "Scheda riepilogativa digitale del paziente", "Blook test on mobile": "Test Blook su cellulare", "Heart rate on smart watch": "Frequenza cardiaca sullo smartwatch", "Digital Camera": "Macchina fotografica digitale", "Bulb": "Bulbo", "Speed": "Velocità", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Cuore in una scatola", "Piggybank in a box": "Salvadanaio in scatola", "Recycle in a box": "Riciclare in una scatola", "Gift in a box": "Regalo in una scatola", "Bell": "Campana", "Bubbles": "Bolle", "Opening case": "Custodia apribile", "DNA": "DNA", "Speakers": "Altoparlanti", "Headphones": "Cuffia", "Wireless Charger": "Caricabatterie wireless"],
        "es": ["Clothes Stack": "Pila de ropa", "Bag": "Bolsa", "Recycling": "Reciclaje", "Piano": "Piano", "Keys": "Llaves", "Strings": "Instrumentos de cuerda", "Watch": "Reloj", "Beehive": "Colmena", "Test Tube": "Tubo de ensayo", "Pineapple": "Piña", "Tree": "Árbol", "Milk Tettra pack": "Pack Leche Tettra", "Pen": "Pluma", "Map": "Mapa", "Book": "Libro", "Digital patient summary board": "Tablero digital de resumen del paciente", "Blook test on mobile": "Prueba de Blook en el móvil", "Heart rate on smart watch": "Frecuencia cardíaca en un reloj inteligente", "Digital Camera": "Cámara digital", "Bulb": "Bombilla", "Speed": "Velocidad", "Rugby": "Rugby", "Go-pro": "Ir a la prenda", "Heart in a box": "Corazón en una caja", "Piggybank in a box": "Hucha en caja", "Recycle in a box": "Reciclar en una caja", "Gift in a box": "Regalo en caja", "Bell": "Campana", "Bubbles": "Burbujas", "Opening case": "Caja de apertura", "DNA": "ADN", "Speakers": "Altavoces", "Headphones": "Auriculares", "Wireless Charger": "Cargador inalámbrico"],
        "zh": ["Clothes Stack": "衣物堆叠", "Bag": "袋", "Recycling": "回收", "Piano": "钢琴", "Keys": "钥匙", "Strings": "字符串", "Watch": "看", "Beehive": "蜂窝", "Test Tube": "试管", "Pineapple": "菠萝", "Tree": "树", "Milk Tettra pack": "Milk Tettra 包装", "Pen": "笔", "Map": "地图", "Book": "书", "Digital patient summary board": "数字患者汇总板", "Blook test on mobile": "移动端 Blook 测试", "Heart rate on smart watch": "智能手表上的心率", "Digital Camera": "数码相机", "Bulb": "灯泡", "Speed": "速度", "Rugby": "橄榄球", "Go-pro": "Go-pro 认证", "Heart in a box": "心装盒", "Piggybank in a box": "盒子里的存钱罐", "Recycle in a box": "盒中回收", "Gift in a box": "盒装礼品", "Bell": "钟", "Bubbles": "泡沫", "Opening case": "开箱", "DNA": "脱氧核糖核酸", "Speakers": "扬声器", "Headphones": "耳机", "Wireless Charger": "无线充电器"],
        "fr-CA": ["Clothes Stack": "Pile de vêtements", "Bag": "Sac", "Recycling": "Recyclage", "Piano": "Piano", "Keys": "Clés", "Strings": "Cordes", "Watch": "Regarder", "Beehive": "Ruche", "Test Tube": "Éprouvette", "Pineapple": "Ananas", "Tree": "Arbre", "Milk Tettra pack": "Paquet de lait Tettra", "Pen": "Stylo", "Map": "Carte", "Book": "Réserver", "Digital patient summary board": "Tableau de synthèse numérique des patients", "Blook test on mobile": "Test Blook sur mobile", "Heart rate on smart watch": "Fréquence cardiaque sur montre intelligente", "Digital Camera": "Appareil photo numérique", "Bulb": "Ampoule", "Speed": "Rapidité", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Cœur dans une boîte", "Piggybank in a box": "Tirelire dans une boîte", "Recycle in a box": "Recycler dans une boîte", "Gift in a box": "Cadeau dans une boîte", "Bell": "Bell", "Bubbles": "Bulles", "Opening case": "Dossier d’ouverture", "DNA": "ADN", "Speakers": "Conférenciers", "Headphones": "Casque d’écoute", "Wireless Charger": "Chargeur sans fil"],
        "en-NZ": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "vi": ["Clothes Stack": "Xếp quần áo", "Bag": "Túi", "Recycling": "Tái chế", "Piano": "Dương cầm", "Keys": "Phím", "Strings": "Dây", "Watch": "Xem", "Beehive": "Tổ ong", "Test Tube": "Ống nghiệm", "Pineapple": "Dứa", "Tree": "Cây", "Milk Tettra pack": "Gói sữa Tettra", "Pen": "Bút", "Map": "Bản đồ", "Book": "Sách", "Digital patient summary board": "Bảng tóm tắt bệnh nhân kỹ thuật số", "Blook test on mobile": "Kiểm tra Blook trên thiết bị di động", "Heart rate on smart watch": "Nhịp tim trên đồng hồ thông minh", "Digital Camera": "Máy ảnh kỹ thuật số", "Bulb": "Củ", "Speed": "Tốc độ", "Rugby": "Bóng bầu dục", "Go-pro": "Đi chuyên nghiệp", "Heart in a box": "Trái tim trong hộp", "Piggybank in a box": "Piggybank trong một chiếc hộp", "Recycle in a box": "Tái chế trong hộp", "Gift in a box": "Quà tặng trong hộp", "Bell": "Chuông", "Bubbles": "Bong bóng", "Opening case": "Mở trường hợp", "DNA": "DNA", "Speakers": "Loa", "Headphones": "Tai nghe", "Wireless Charger": "Bộ sạc không dây"],
        "fr-BE": ["Clothes Stack": "Pile de vêtements", "Bag": "Sac", "Recycling": "Recyclage", "Piano": "Piano", "Keys": "Clés", "Strings": "Cordes", "Watch": "Montre", "Beehive": "Ruche", "Test Tube": "Éprouvette", "Pineapple": "Ananas", "Tree": "Arbre", "Milk Tettra pack": "Pack de lait Tettra", "Pen": "Stylo", "Map": "Carte", "Book": "Livre", "Digital patient summary board": "Tableau récapitulatif numérique du patient", "Blook test on mobile": "Test Blook sur mobile", "Heart rate on smart watch": "Fréquence cardiaque sur la montre intelligente", "Digital Camera": "Appareil photo numérique", "Bulb": "Bulbe", "Speed": "Vitesse", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Coeur dans une boîte", "Piggybank in a box": "Tirelire dans une boîte", "Recycle in a box": "Recycler dans une boîte", "Gift in a box": "Cadeau dans une boîte", "Bell": "Cloche", "Bubbles": "Bulles", "Opening case": "Ouverture du boîtier", "DNA": "ADN", "Speakers": "Haut-parleurs", "Headphones": "Casque", "Wireless Charger": "Chargeur sans fil"],
        "ja": ["Clothes Stack": "洋服スタック", "Bag": "袋", "Recycling": "再利用", "Piano": "ピアノ", "Keys": "キー", "Strings": "ストリングス", "Watch": "時計", "Beehive": "蜂の巣", "Test Tube": "試験管", "Pineapple": "パイナップル", "Tree": "木", "Milk Tettra pack": "ミルクテトラパック", "Pen": "ペン", "Map": "地図", "Book": "本", "Digital patient summary board": "デジタル患者サマリーボード", "Blook test on mobile": "モバイルでのBlookテスト", "Heart rate on smart watch": "スマートウォッチの心拍数", "Digital Camera": "デジカメ", "Bulb": "電球", "Speed": "速度", "Rugby": "ラグビー", "Go-pro": "囲碁プロ", "Heart in a box": "箱の中の心", "Piggybank in a box": "箱の中の貯金箱", "Recycle in a box": "箱にリサイクルする", "Gift in a box": "箱の中のギフト", "Bell": "鐘", "Bubbles": "泡", "Opening case": "ケースを開く", "DNA": "デオキシリボ核酸", "Speakers": "スピーカー", "Headphones": "ヘッドフォン", "Wireless Charger": "ワイヤレス充電器"],
        "en-SG": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "it-CH": ["Clothes Stack": "Pila di vestiti", "Bag": "Sacco", "Recycling": "Riciclaggio", "Piano": "Pianoforte", "Keys": "Chiavi", "Strings": "Stringhe", "Watch": "Orologio", "Beehive": "Alveare", "Test Tube": "Provetta", "Pineapple": "Ananas", "Tree": "Albero", "Milk Tettra pack": "Confezione Tettra al latte", "Pen": "Penna", "Map": "Mappa", "Book": "Libro", "Digital patient summary board": "Scheda riepilogativa digitale del paziente", "Blook test on mobile": "Test Blook su cellulare", "Heart rate on smart watch": "Frequenza cardiaca sullo smartwatch", "Digital Camera": "Macchina fotografica digitale", "Bulb": "Bulbo", "Speed": "Velocità", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Cuore in una scatola", "Piggybank in a box": "Salvadanaio in scatola", "Recycle in a box": "Riciclare in una scatola", "Gift in a box": "Regalo in una scatola", "Bell": "Campana", "Bubbles": "Bolle", "Opening case": "Custodia apribile", "DNA": "DNA", "Speakers": "Altoparlanti", "Headphones": "Cuffia", "Wireless Charger": "Caricabatterie wireless"],
        "fr-FR": ["Clothes Stack": "Pile de vêtements", "Bag": "Sac", "Recycling": "Recyclage", "Piano": "Piano", "Keys": "Clés", "Strings": "Cordes", "Watch": "Montre", "Beehive": "Ruche", "Test Tube": "Éprouvette", "Pineapple": "Ananas", "Tree": "Arbre", "Milk Tettra pack": "Pack de lait Tettra", "Pen": "Stylo", "Map": "Carte", "Book": "Livre", "Digital patient summary board": "Tableau récapitulatif numérique du patient", "Blook test on mobile": "Test Blook sur mobile", "Heart rate on smart watch": "Fréquence cardiaque sur la montre intelligente", "Digital Camera": "Appareil photo numérique", "Bulb": "Bulbe", "Speed": "Vitesse", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Coeur dans une boîte", "Piggybank in a box": "Tirelire dans une boîte", "Recycle in a box": "Recycler dans une boîte", "Gift in a box": "Cadeau dans une boîte", "Bell": "Cloche", "Bubbles": "Bulles", "Opening case": "Ouverture du boîtier", "DNA": "ADN", "Speakers": "Haut-parleurs", "Headphones": "Casque", "Wireless Charger": "Chargeur sans fil"],
        "vi-VN": ["Clothes Stack": "Xếp quần áo", "Bag": "Túi", "Recycling": "Tái chế", "Piano": "Dương cầm", "Keys": "Phím", "Strings": "Dây", "Watch": "Xem", "Beehive": "Tổ ong", "Test Tube": "Ống nghiệm", "Pineapple": "Dứa", "Tree": "Cây", "Milk Tettra pack": "Gói sữa Tettra", "Pen": "Bút", "Map": "Bản đồ", "Book": "Sách", "Digital patient summary board": "Bảng tóm tắt bệnh nhân kỹ thuật số", "Blook test on mobile": "Kiểm tra Blook trên thiết bị di động", "Heart rate on smart watch": "Nhịp tim trên đồng hồ thông minh", "Digital Camera": "Máy ảnh kỹ thuật số", "Bulb": "Củ", "Speed": "Tốc độ", "Rugby": "Bóng bầu dục", "Go-pro": "Đi chuyên nghiệp", "Heart in a box": "Trái tim trong hộp", "Piggybank in a box": "Piggybank trong một chiếc hộp", "Recycle in a box": "Tái chế trong hộp", "Gift in a box": "Quà tặng trong hộp", "Bell": "Chuông", "Bubbles": "Bong bóng", "Opening case": "Mở trường hợp", "DNA": "DNA", "Speakers": "Loa", "Headphones": "Tai nghe", "Wireless Charger": "Bộ sạc không dây"],
        "en-GB": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-KE": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-KH": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "bg": ["Clothes Stack": "Купчина дрехи", "Bag": "Чанта", "Recycling": "Рециклиране", "Piano": "Пиано", "Keys": "Ключове", "Strings": "Струни", "Watch": "Гледате", "Beehive": "Кошер", "Test Tube": "Епруветка", "Pineapple": "Ананас", "Tree": "Дърво", "Milk Tettra pack": "Опаковка Milk Tettra", "Pen": "Писалка", "Map": "Карта", "Book": "Книга", "Digital patient summary board": "Дигитално обобщение на пациента", "Blook test on mobile": "Тест Blook на мобилни устройства", "Heart rate on smart watch": "Сърдечен ритъм на смарт часовник", "Digital Camera": "Цифров фотоапарат", "Bulb": "Крушка", "Speed": "Скорост", "Rugby": "Ръгби", "Go-pro": "Вървете професионално", "Heart in a box": "Сърце в кутия", "Piggybank in a box": "Касичка в кутия", "Recycle in a box": "Рециклирайте в кутия", "Gift in a box": "Подарък в кутия", "Bell": "Камбана", "Bubbles": "Мехурчета", "Opening case": "Отваряне на случай", "DNA": "ДНК", "Speakers": "Високоговорители", "Headphones": "Слушалки", "Wireless Charger": "Безжично зарядно устройство"],
        "en-CH": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-KR": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "ar-AE": ["Clothes Stack": "كومة الملابس", "Bag": "كيس", "Recycling": "اعاده التدوير", "Piano": "بيانو", "Keys": "المفاتيح", "Strings": "سلاسل", "Watch": "شاهد", "Beehive": "جبح", "Test Tube": "أنبوب الاختبار", "Pineapple": "أناناس", "Tree": "شجرة", "Milk Tettra pack": "عبوة تيترا الحليب", "Pen": "قلم", "Map": "خريطة", "Book": "كتاب", "Digital patient summary board": "لوحة ملخص رقمية للمريض", "Blook test on mobile": "اختبار Blook على الهاتف المحمول", "Heart rate on smart watch": "معدل ضربات القلب على الساعة الذكية", "Digital Camera": "كاميرا رقمية", "Bulb": "لمبه", "Speed": "سرعة", "Rugby": "الركبي", "Go-pro": "جو برو", "Heart in a box": "قلب في صندوق", "Piggybank in a box": "أصبع في صندوق", "Recycle in a box": "إعادة التدوير في صندوق", "Gift in a box": "هدية في صندوق", "Bell": "جرس", "Bubbles": "الفقاقيع", "Opening case": "فتح العلبة", "DNA": "دنا", "Speakers": "المتكلمون", "Headphones": "سماعات الراس", "Wireless Charger": "شاحن لاسلكي"],
        "fr": ["Clothes Stack": "Pile de vêtements", "Bag": "Sac", "Recycling": "Recyclage", "Piano": "Piano", "Keys": "Clés", "Strings": "Cordes", "Watch": "Montre", "Beehive": "Ruche", "Test Tube": "Éprouvette", "Pineapple": "Ananas", "Tree": "Arbre", "Milk Tettra pack": "Pack de lait Tettra", "Pen": "Stylo", "Map": "Carte", "Book": "Livre", "Digital patient summary board": "Tableau récapitulatif numérique du patient", "Blook test on mobile": "Test Blook sur mobile", "Heart rate on smart watch": "Fréquence cardiaque sur la montre intelligente", "Digital Camera": "Appareil photo numérique", "Bulb": "Bulbe", "Speed": "Vitesse", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Coeur dans une boîte", "Piggybank in a box": "Tirelire dans une boîte", "Recycle in a box": "Recycler dans une boîte", "Gift in a box": "Cadeau dans une boîte", "Bell": "Cloche", "Bubbles": "Bulles", "Opening case": "Ouverture du boîtier", "DNA": "ADN", "Speakers": "Haut-parleurs", "Headphones": "Casque", "Wireless Charger": "Chargeur sans fil"],
        "en-CN": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "de-AT": ["Clothes Stack": "Kleider-Stapel", "Bag": "Tasche", "Recycling": "Recycling", "Piano": "Klavier", "Keys": "Tasten", "Strings": "Streichinstrumente", "Watch": "Uhr", "Beehive": "Bienenstock", "Test Tube": "Reagenzglas", "Pineapple": "Ananas", "Tree": "Baum", "Milk Tettra pack": "Milch Tettra Packung", "Pen": "Feder", "Map": "Landkarte", "Book": "Buch", "Digital patient summary board": "Digitale Patientenübersicht", "Blook test on mobile": "Blook-Test auf dem Handy", "Heart rate on smart watch": "Herzfrequenz auf der Smartwatch", "Digital Camera": "Digitalkamera", "Bulb": "Glühlampe", "Speed": "Geschwindigkeit", "Rugby": "Rugby", "Go-pro": "Auf Deutsch", "Heart in a box": "Herz in der Schachtel", "Piggybank in a box": "Sparschwein in der Schachtel", "Recycle in a box": "Recycling in einer Box", "Gift in a box": "Geschenk in einer Schachtel", "Bell": "Glocke", "Bubbles": "Blasen", "Opening case": "Öffnen des Gehäuses", "DNA": "DNS", "Speakers": "Lautsprecher", "Headphones": "Kopfhörer", "Wireless Charger": "Kabelloses Ladegerät"],
        "fr-CH": ["Clothes Stack": "Pile de vêtements", "Bag": "Sac", "Recycling": "Recyclage", "Piano": "Piano", "Keys": "Clés", "Strings": "Cordes", "Watch": "Montre", "Beehive": "Ruche", "Test Tube": "Éprouvette", "Pineapple": "Ananas", "Tree": "Arbre", "Milk Tettra pack": "Pack de lait Tettra", "Pen": "Stylo", "Map": "Carte", "Book": "Livre", "Digital patient summary board": "Tableau récapitulatif numérique du patient", "Blook test on mobile": "Test Blook sur mobile", "Heart rate on smart watch": "Fréquence cardiaque sur la montre intelligente", "Digital Camera": "Appareil photo numérique", "Bulb": "Bulbe", "Speed": "Vitesse", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Coeur dans une boîte", "Piggybank in a box": "Tirelire dans une boîte", "Recycle in a box": "Recycler dans une boîte", "Gift in a box": "Cadeau dans une boîte", "Bell": "Cloche", "Bubbles": "Bulles", "Opening case": "Ouverture du boîtier", "DNA": "ADN", "Speakers": "Haut-parleurs", "Headphones": "Casque", "Wireless Charger": "Chargeur sans fil"],
        "sk": ["Clothes Stack": "Stoh oblečenia", "Bag": "Taška", "Recycling": "Recyklovanie", "Piano": "Klavír", "Keys": "Kľúče", "Strings": "Sláčiky", "Watch": "Hodinky", "Beehive": "Úľ", "Test Tube": "Skúmavky", "Pineapple": "Ananás", "Tree": "Strom", "Milk Tettra pack": "Balíček Milk Tettra", "Pen": "Pero", "Map": "Mapa", "Book": "Kniha", "Digital patient summary board": "Digitálna súhrnná tabuľa pacienta", "Blook test on mobile": "Test Blook na mobile", "Heart rate on smart watch": "Srdcová frekvencia na inteligentných hodinkách", "Digital Camera": "Digitálny fotoaparát", "Bulb": "Žiarovka", "Speed": "Rýchlosť", "Rugby": "Ragby", "Go-pro": "Go-pro", "Heart in a box": "Srdce v krabici", "Piggybank in a box": "Prasiatko v krabici", "Recycle in a box": "Recyklácia v krabici", "Gift in a box": "Darček v krabičke", "Bell": "Zvon", "Bubbles": "Bubliny", "Opening case": "Otváracie puzdro", "DNA": "DNA", "Speakers": "Reproduktory", "Headphones": "Slúchadlá", "Wireless Charger": "Bezdrôtová nabíjačka"],
        "en-TH": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-CZ": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "cs-CZ": ["Clothes Stack": "Zásobník oblečení", "Bag": "Pytel", "Recycling": "Recyklace", "Piano": "Klavír", "Keys": "Klíče", "Strings": "Řetězce", "Watch": "Sledovat", "Beehive": "Úl", "Test Tube": "Zkumavka", "Pineapple": "Ananas", "Tree": "Strom", "Milk Tettra pack": "Mléčný balíček Tettra", "Pen": "Pero", "Map": "Mapa", "Book": "Kniha", "Digital patient summary board": "Digitální souhrnná tabule pacientů", "Blook test on mobile": "Test Blook na mobilu", "Heart rate on smart watch": "Tepová frekvence na chytrých hodinkách", "Digital Camera": "Digitální fotoaparát", "Bulb": "Žárovka", "Speed": "Rychlost", "Rugby": "Ragby", "Go-pro": "Go-pro", "Heart in a box": "Srdíčko v krabici", "Piggybank in a box": "Prasátko v krabici", "Recycle in a box": "Recyklace v krabici", "Gift in a box": "Dárek v krabici", "Bell": "Zvon", "Bubbles": "Bubliny", "Opening case": "Otevírací případ", "DNA": "DNA", "Speakers": "Reproduktory", "Headphones": "Sluchátka", "Wireless Charger": "Bezdrátová nabíječka"],
        "en-PH": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-PK": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "en-LK": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "de-DE": ["Clothes Stack": "Kleider-Stapel", "Bag": "Tasche", "Recycling": "Recycling", "Piano": "Klavier", "Keys": "Tasten", "Strings": "Streichinstrumente", "Watch": "Uhr", "Beehive": "Bienenstock", "Test Tube": "Reagenzglas", "Pineapple": "Ananas", "Tree": "Baum", "Milk Tettra pack": "Milch Tettra Packung", "Pen": "Feder", "Map": "Landkarte", "Book": "Buch", "Digital patient summary board": "Digitale Patientenübersicht", "Blook test on mobile": "Blook-Test auf dem Handy", "Heart rate on smart watch": "Herzfrequenz auf der Smartwatch", "Digital Camera": "Digitalkamera", "Bulb": "Glühlampe", "Speed": "Geschwindigkeit", "Rugby": "Rugby", "Go-pro": "Auf Deutsch", "Heart in a box": "Herz in der Schachtel", "Piggybank in a box": "Sparschwein in der Schachtel", "Recycle in a box": "Recycling in einer Box", "Gift in a box": "Geschenk in einer Schachtel", "Bell": "Glocke", "Bubbles": "Blasen", "Opening case": "Öffnen des Gehäuses", "DNA": "DNS", "Speakers": "Lautsprecher", "Headphones": "Kopfhörer", "Wireless Charger": "Kabelloses Ladegerät"],
        "ko": ["Clothes Stack": "옷 스택", "Bag": "가방", "Recycling": "재활용", "Piano": "피아노", "Keys": "키", "Strings": "문자열", "Watch": "시계", "Beehive": "벌집", "Test Tube": "시험관", "Pineapple": "파인애플", "Tree": "나무", "Milk Tettra pack": "밀크 테트라 팩", "Pen": "펜", "Map": "지도", "Book": "책", "Digital patient summary board": "디지털 환자 요약 게시판", "Blook test on mobile": "모바일에서 Blook 테스트", "Heart rate on smart watch": "스마트 워치의 심박수", "Digital Camera": "디지털 카메라", "Bulb": "전구", "Speed": "속도", "Rugby": "럭비", "Go-pro": "고프로", "Heart in a box": "상자 속의 하트", "Piggybank in a box": "상자 속의 돼지 저금통", "Recycle in a box": "상자에 넣어 재활용", "Gift in a box": "상자에 담긴 선물", "Bell": "종", "Bubbles": "거품", "Opening case": "오프닝 케이스", "DNA": "디에이지", "Speakers": "스피커", "Headphones": "헤드폰", "Wireless Charger": "무선 충전기"],
        "zh-TW": ["Clothes Stack": "衣物堆疊", "Bag": "袋", "Recycling": "回收", "Piano": "鋼琴", "Keys": "鑰匙", "Strings": "字串", "Watch": "看", "Beehive": "蜂窩", "Test Tube": "試管", "Pineapple": "鳳梨", "Tree": "樹", "Milk Tettra pack": "Milk Tettra 包裝", "Pen": "筆", "Map": "地圖", "Book": "書", "Digital patient summary board": "數位患者匯總板", "Blook test on mobile": "移動端 Blook 測試", "Heart rate on smart watch": "智慧手錶上的心率", "Digital Camera": "數碼相機", "Bulb": "燈泡", "Speed": "速度", "Rugby": "橄欖球", "Go-pro": "Go-pro 認證", "Heart in a box": "心裝盒", "Piggybank in a box": "盒子里的存錢罐", "Recycle in a box": "盒中回收", "Gift in a box": "盒裝禮品", "Bell": "鐘", "Bubbles": "泡沫", "Opening case": "開箱", "DNA": "去氧核糖核酸", "Speakers": "揚聲器", "Headphones": "耳機", "Wireless Charger": "無線充電器"],
        "zh-HK": ["Clothes Stack": "衣物堆疊", "Bag": "袋", "Recycling": "回收", "Piano": "鋼琴", "Keys": "鎖匙", "Strings": "字符串", "Watch": "看", "Beehive": "蜂窩", "Test Tube": "試管", "Pineapple": "菠蘿", "Tree": "樹", "Milk Tettra pack": "Milk Tettra包裝", "Pen": "筆", "Map": "地圖", "Book": "書", "Digital patient summary board": "數字患者匯總板", "Blook test on mobile": "移動端Blook測試", "Heart rate on smart watch": "智能手錶上嘅心率", "Digital Camera": "數碼相機", "Bulb": "燈泡", "Speed": "速度", "Rugby": "橄欖毬", "Go-pro": "Go-pro認證", "Heart in a box": "心裝盒", "Piggybank in a box": "盒子里嘅儲錢罐", "Recycle in a box": "盒中回收", "Gift in a box": "盒裝禮品", "Bell": "鐘", "Bubbles": "泡沫", "Opening case": "開箱", "DNA": "脫氧核糖核酸", "Speakers": "揚聲器", "Headphones": "耳機", "Wireless Charger": "無線充電器"],
        "ko-KR": ["Clothes Stack": "옷 스택", "Bag": "가방", "Recycling": "재활용", "Piano": "피아노", "Keys": "키", "Strings": "문자열", "Watch": "시계", "Beehive": "벌집", "Test Tube": "시험관", "Pineapple": "파인애플", "Tree": "나무", "Milk Tettra pack": "밀크 테트라 팩", "Pen": "펜", "Map": "지도", "Book": "책", "Digital patient summary board": "디지털 환자 요약 게시판", "Blook test on mobile": "모바일에서 Blook 테스트", "Heart rate on smart watch": "스마트 워치의 심박수", "Digital Camera": "디지털 카메라", "Bulb": "전구", "Speed": "속도", "Rugby": "럭비", "Go-pro": "고프로", "Heart in a box": "상자 속의 하트", "Piggybank in a box": "상자 속의 돼지 저금통", "Recycle in a box": "상자에 넣어 재활용", "Gift in a box": "상자에 담긴 선물", "Bell": "종", "Bubbles": "거품", "Opening case": "오프닝 케이스", "DNA": "디에이지", "Speakers": "스피커", "Headphones": "헤드폰", "Wireless Charger": "무선 충전기"],
        "pt-BR": ["Clothes Stack": "Pilha de roupas", "Bag": "Saco", "Recycling": "Reciclagem", "Piano": "Piano", "Keys": "Chaves", "Strings": "Strings", "Watch": "Relógio", "Beehive": "Colmeia", "Test Tube": "Tubo de ensaio", "Pineapple": "Abacaxi", "Tree": "Árvore", "Milk Tettra pack": "Pacote Milk Tettra", "Pen": "Caneta", "Map": "Mapa", "Book": "Livro", "Digital patient summary board": "Quadro digital de resumo do paciente", "Blook test on mobile": "Teste Blook no celular", "Heart rate on smart watch": "Frequência cardíaca no relógio inteligente", "Digital Camera": "Câmera digital", "Bulb": "Lâmpada", "Speed": "Velocidade", "Rugby": "Rúgbi", "Go-pro": "Ir pro", "Heart in a box": "Coração em uma caixa", "Piggybank in a box": "Cofrinho em uma caixa", "Recycle in a box": "Reciclar em uma caixa", "Gift in a box": "Presente em uma caixa", "Bell": "Sino", "Bubbles": "Bolhas", "Opening case": "Caixa de abertura", "DNA": "ADN", "Speakers": "Falantes", "Headphones": "Auscultadores", "Wireless Charger": "Carregador sem fio"],
        "en-HK": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "sk-SK": ["Clothes Stack": "Stoh oblečenia", "Bag": "Taška", "Recycling": "Recyklovanie", "Piano": "Klavír", "Keys": "Kľúče", "Strings": "Sláčiky", "Watch": "Hodinky", "Beehive": "Úľ", "Test Tube": "Skúmavky", "Pineapple": "Ananás", "Tree": "Strom", "Milk Tettra pack": "Balíček Milk Tettra", "Pen": "Pero", "Map": "Mapa", "Book": "Kniha", "Digital patient summary board": "Digitálna súhrnná tabuľa pacienta", "Blook test on mobile": "Test Blook na mobile", "Heart rate on smart watch": "Srdcová frekvencia na inteligentných hodinkách", "Digital Camera": "Digitálny fotoaparát", "Bulb": "Žiarovka", "Speed": "Rýchlosť", "Rugby": "Ragby", "Go-pro": "Go-pro", "Heart in a box": "Srdce v krabici", "Piggybank in a box": "Prasiatko v krabici", "Recycle in a box": "Recyklácia v krabici", "Gift in a box": "Darček v krabičke", "Bell": "Zvon", "Bubbles": "Bubliny", "Opening case": "Otváracie puzdro", "DNA": "DNA", "Speakers": "Reproduktory", "Headphones": "Slúchadlá", "Wireless Charger": "Bezdrôtová nabíjačka"],
        "en-PT": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "es-ES": ["Clothes Stack": "Pila de ropa", "Bag": "Bolsa", "Recycling": "Reciclaje", "Piano": "Piano", "Keys": "Llaves", "Strings": "Instrumentos de cuerda", "Watch": "Reloj", "Beehive": "Colmena", "Test Tube": "Tubo de ensayo", "Pineapple": "Piña", "Tree": "Árbol", "Milk Tettra pack": "Pack Leche Tettra", "Pen": "Pluma", "Map": "Mapa", "Book": "Libro", "Digital patient summary board": "Tablero digital de resumen del paciente", "Blook test on mobile": "Prueba de Blook en el móvil", "Heart rate on smart watch": "Frecuencia cardíaca en un reloj inteligente", "Digital Camera": "Cámara digital", "Bulb": "Bombilla", "Speed": "Velocidad", "Rugby": "Rugby", "Go-pro": "Ir a la prenda", "Heart in a box": "Corazón en una caja", "Piggybank in a box": "Hucha en caja", "Recycle in a box": "Reciclar en una caja", "Gift in a box": "Regalo en caja", "Bell": "Campana", "Bubbles": "Burbujas", "Opening case": "Caja de apertura", "DNA": "ADN", "Speakers": "Altavoces", "Headphones": "Auriculares", "Wireless Charger": "Cargador inalámbrico"],
        "en-DK": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"],
        "cs": ["Clothes Stack": "Zásobník oblečení", "Bag": "Pytel", "Recycling": "Recyklace", "Piano": "Klavír", "Keys": "Klíče", "Strings": "Řetězce", "Watch": "Sledovat", "Beehive": "Úl", "Test Tube": "Zkumavka", "Pineapple": "Ananas", "Tree": "Strom", "Milk Tettra pack": "Mléčný balíček Tettra", "Pen": "Pero", "Map": "Mapa", "Book": "Kniha", "Digital patient summary board": "Digitální souhrnná tabule pacientů", "Blook test on mobile": "Test Blook na mobilu", "Heart rate on smart watch": "Tepová frekvence na chytrých hodinkách", "Digital Camera": "Digitální fotoaparát", "Bulb": "Žárovka", "Speed": "Rychlost", "Rugby": "Ragby", "Go-pro": "Go-pro", "Heart in a box": "Srdíčko v krabici", "Piggybank in a box": "Prasátko v krabici", "Recycle in a box": "Recyklace v krabici", "Gift in a box": "Dárek v krabici", "Bell": "Zvon", "Bubbles": "Bubliny", "Opening case": "Otevírací případ", "DNA": "DNA", "Speakers": "Reproduktory", "Headphones": "Sluchátka", "Wireless Charger": "Bezdrátová nabíječka"],
        "it-IT": ["Clothes Stack": "Pila di vestiti", "Bag": "Sacco", "Recycling": "Riciclaggio", "Piano": "Pianoforte", "Keys": "Chiavi", "Strings": "Stringhe", "Watch": "Orologio", "Beehive": "Alveare", "Test Tube": "Provetta", "Pineapple": "Ananas", "Tree": "Albero", "Milk Tettra pack": "Confezione Tettra al latte", "Pen": "Penna", "Map": "Mappa", "Book": "Libro", "Digital patient summary board": "Scheda riepilogativa digitale del paziente", "Blook test on mobile": "Test Blook su cellulare", "Heart rate on smart watch": "Frequenza cardiaca sullo smartwatch", "Digital Camera": "Macchina fotografica digitale", "Bulb": "Bulbo", "Speed": "Velocità", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Cuore in una scatola", "Piggybank in a box": "Salvadanaio in scatola", "Recycle in a box": "Riciclare in una scatola", "Gift in a box": "Regalo in una scatola", "Bell": "Campana", "Bubbles": "Bolle", "Opening case": "Custodia apribile", "DNA": "DNA", "Speakers": "Altoparlanti", "Headphones": "Cuffia", "Wireless Charger": "Caricabatterie wireless"],
        "th": ["Clothes Stack": "กองเสื้อผ้า", "Bag": "ถุง", "Recycling": "รี ไซ เคิล", "Piano": "เปียโน", "Keys": "คีย์", "Strings": "พันธะ", "Watch": "ดู", "Beehive": "รังผึ้ง", "Test Tube": "หลอดทดลอง", "Pineapple": "สับปะรด", "Tree": "ต้นไม้", "Milk Tettra pack": "แพ็คนม Tettra", "Pen": "ปากกา", "Map": "แผนที่", "Book": "หนังสือ", "Digital patient summary board": "กระดานสรุปผู้ป่วยดิจิทัล", "Blook test on mobile": "การทดสอบ Blook บนมือถือ", "Heart rate on smart watch": "อัตราการเต้นของหัวใจบนสมาร์ทวอทช์", "Digital Camera": "กล้องดิจิตอล", "Bulb": "หลอดไฟ", "Speed": "ความเร็ว", "Rugby": "รักบี้", "Go-pro": "โกโปร", "Heart in a box": "หัวใจในกล่อง", "Piggybank in a box": "กระปุกออมสินในกล่อง", "Recycle in a box": "รีไซเคิลในกล่อง", "Gift in a box": "ของขวัญในกล่อง", "Bell": "ระฆัง", "Bubbles": "ฟอง", "Opening case": "เปิดเคส", "DNA": "ดีเอ็นเอ", "Speakers": "ลำโพง", "Headphones": "หู ฟัง", "Wireless Charger": "เครื่องชาร์จไร้สาย"],
        "sv-SE": ["Clothes Stack": "Kläder Stack", "Bag": "Påse", "Recycling": "Återvinning", "Piano": "Piano", "Keys": "Nycklar", "Strings": "Strängar", "Watch": "Klocka", "Beehive": "Bikupa", "Test Tube": "Provrör", "Pineapple": "Ananas", "Tree": "Träd", "Milk Tettra pack": "Mjölk Tetra-förpackning", "Pen": "Penna", "Map": "Karta", "Book": "Bok", "Digital patient summary board": "Digital patientöversiktstavla", "Blook test on mobile": "Blook test på mobilen", "Heart rate on smart watch": "Hjärtfrekvens på smart klocka", "Digital Camera": "Digitalkamera", "Bulb": "Glödlampa", "Speed": "Hastighet", "Rugby": "Rugby", "Go-pro": "Go-proffs", "Heart in a box": "Hjärta i en ask", "Piggybank in a box": "Spargris i en låda", "Recycle in a box": "Återvinn i en låda", "Gift in a box": "Gåva i en låda", "Bell": "Klocka", "Bubbles": "Bubblor", "Opening case": "Öppningsbar låda", "DNA": "DNA", "Speakers": "Högtalare", "Headphones": "Hörlurar", "Wireless Charger": "Trådlös laddare"],
        "da-DK": ["Clothes Stack": "Tøjstak", "Bag": "Taske", "Recycling": "Genbrug", "Piano": "Klaver", "Keys": "Nøgler", "Strings": "Strenge", "Watch": "Ur", "Beehive": "Bikube", "Test Tube": "Reagensglas", "Pineapple": "Ananas", "Tree": "Træ", "Milk Tettra pack": "Mælk Tettra pakke", "Pen": "Pen", "Map": "Kort", "Book": "Bog", "Digital patient summary board": "Digital patientoversigt", "Blook test on mobile": "Blook-test på mobil", "Heart rate on smart watch": "Puls på smartur", "Digital Camera": "Digitalkamera", "Bulb": "Pære", "Speed": "Fart", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Hjerte i æske", "Piggybank in a box": "Sparegris i en kasse", "Recycle in a box": "Genbrug i en kasse", "Gift in a box": "Gave i æske", "Bell": "Klokke", "Bubbles": "Bobler", "Opening case": "Åbning af sag", "DNA": "DNA", "Speakers": "Højttalere", "Headphones": "Hovedtelefoner", "Wireless Charger": "Trådløs oplader"],
        "pl": ["Clothes Stack": "Stos ubrań", "Bag": "Torba", "Recycling": "Recykling", "Piano": "Pianino", "Keys": "Klucze", "Strings": "Ciągi", "Watch": "Zegarek", "Beehive": "Ul", "Test Tube": "Probówka", "Pineapple": "Ananas", "Tree": "Drzewo", "Milk Tettra pack": "Pakiet Milk Tettra", "Pen": "Pióro", "Map": "Mapa", "Book": "Książka", "Digital patient summary board": "Cyfrowa tablica kartotekowa pacjenta", "Blook test on mobile": "Test Blook na urządzeniach mobilnych", "Heart rate on smart watch": "Tętno na inteligentnym zegarku", "Digital Camera": "Aparat cyfrowy", "Bulb": "Żarówka", "Speed": "Szybkość", "Rugby": "Rugby", "Go-pro": "Idź profesjonalnie", "Heart in a box": "Serce w pudełku", "Piggybank in a box": "Skarbonka w pudełku", "Recycle in a box": "Recykling w pudełku", "Gift in a box": "Prezent w pudełku", "Bell": "Dzwon", "Bubbles": "Pęcherzyki", "Opening case": "Otwieranie walizki", "DNA": "DNA", "Speakers": "Głośniki", "Headphones": "Słuchawki", "Wireless Charger": "Bezprzewodowa ładowarka"],
        "he": ["Clothes Stack": "ערימת בגדים", "Bag": "תיק", "Recycling": "מיחזור", "Piano": "פסנתר", "Keys": "במקשי", "Strings": "מחרוזות", "Watch": "צפה", "Beehive": "כוורת", "Test Tube": "מבחנה", "Pineapple": "אננס", "Tree": "עץ", "Milk Tettra pack": "חבילת טטרה חלב", "Pen": "עט", "Map": "מפה", "Book": "ספר", "Digital patient summary board": "לוח סיכום מטופל דיגיטלי", "Blook test on mobile": "מבחן Blook במובייל", "Heart rate on smart watch": "דופק בשעון חכם", "Digital Camera": "מצלמה דיגיטלית", "Bulb": "פקעת", "Speed": "מהירות", "Rugby": "רוגבי", "Go-pro": "גו-פרו", "Heart in a box": "לב בקופסה", "Piggybank in a box": "חזירון בקופסה", "Recycle in a box": "מיחזור בקופסה", "Gift in a box": "מתנה בקופסה", "Bell": "פעמון", "Bubbles": "בועות", "Opening case": "תיק פתיחה", "DNA": "דנ א", "Speakers": "רמקולים", "Headphones": "אוזניות", "Wireless Charger": "מטען אלחוטי"],
        "en-ID": ["Clothes Stack": "Clothes Stack", "Bag": "Bag", "Recycling": "Recycling", "Piano": "Piano", "Keys": "Keys", "Strings": "Strings", "Watch": "Watch", "Beehive": "Beehive", "Test Tube": "Test Tube", "Pineapple": "Pineapple", "Tree": "Tree", "Milk Tettra pack": "Milk Tettra pack", "Pen": "Pen", "Map": "Map", "Book": "Book", "Digital patient summary board": "Digital patient summary board", "Blook test on mobile": "Blook test on mobile", "Heart rate on smart watch": "Heart rate on smart watch", "Digital Camera": "Digital Camera", "Bulb": "Bulb", "Speed": "Speed", "Rugby": "Rugby", "Go-pro": "Go-pro", "Heart in a box": "Heart in a box", "Piggybank in a box": "Piggybank in a box", "Recycle in a box": "Recycle in a box", "Gift in a box": "Gift in a box", "Bell": "Bell", "Bubbles": "Bubbles", "Opening case": "Opening case", "DNA": "DNA", "Speakers": "Speakers", "Headphones": "Headphones", "Wireless Charger": "Wireless Charger"]
]



def getLocale(resource) {
    def path = resource.getPath();
    if(path.startsWith("/content/experience-fragments")) {
        path =path.replace("/experience-fragments", "")
        def regex = "^((?:[^/]*\\/){4}[^/]*)";
        def pattern = Pattern.compile(regex);
        def matcher = pattern.matcher(path);
        path = matcher.find() ? matcher.group(1) : path
    }
    path = path.replaceAll('/jcr:content.*', "")
    def page = getPage(path)
    if (page == null){
        println """Page is not found: ${path}"""
        return new Locale("en");
    }
    return page.getLanguage();
}

def translate_SHOWCASE_PANEL(phrase, locale) {
    def localeString = locale.toString();
    def language = locale.getLanguage();

    if(DICTIONARY_SHOWCASE_PANEL.containsKey(localeString) && DICTIONARY_SHOWCASE_PANEL[localeString].containsKey(phrase)) {
        return DICTIONARY_SHOWCASE_PANEL[localeString][phrase];
    } else if (DICTIONARY_SHOWCASE_PANEL.containsKey(language) && DICTIONARY_SHOWCASE_PANEL[language].containsKey(phrase)) {
        return DICTIONARY_SHOWCASE_PANEL[language][phrase];
    } else {
        return phrase;
    }
}

def handleShowcasePanel(homePage) {
    def types = ["artificial-intelligence-in-fashion","demand-is-off-scale","luxury","making-fabrics-from-food","personal-touch","portable-healthcare","smart-home-market","sports-equipment","visual-authenticity","world-of-change","lower-prices"];
    def resourceType ="dhl/components/animated-content/showcase-panel";
    def properties = [
            "imgAltText1" : "Clothes Stack",
            "imgAltText2" : "Bag",
            "imgAltText3" : "Recycling",
            "imgAltText4" : "Piano",
            "imgAltText5" : "Keys",
            "imgAltText6" : "Strings",
            "imgAltText7" : "Watch",
            "imgAltText8" : "Beehive",
            "imgAltText9" : "Test Tube",
            "imgAltText10" : "Pineapple",
            "imgAltText11" : "Tree",
            "imgAltText12" : "Milk Tettra pack",
            "imgAltText13" : "Pen",
            "imgAltText14" : "Map",
            "imgAltText15" : "Book",
            "imgAltText16" : "Digital patient summary board",
            "imgAltText17" : "Blook test on mobile",
            "imgAltText18" : "Heart rate on smart watch",
            "imgAltText19" : "Digital Camera",
            "imgAltText20" : "TV",
            "imgAltText21" : "Bulb",
            "imgAltText22" : "Speed",
            "imgAltText23" : "Rugby",
            "imgAltText24" : "Go-pro",
            "imgAltText25" : "Heart in a box",
            "imgAltText26" : "Piggybank in a box",
            "imgAltText27" : "Recycle in a box",
            "imgAltText28" : "Gift in a box",
            "imgAltText29" : "Bell",
            "imgAltText30" : "Bubbles",
            "imgAltText31" : "Opening case",
            "imgAltText32" : "DNA",
            "imgAltText33" : "Speakers",
            "imgAltText34" : "Headphones",
            "imgAltText35" : "Wireless Charger"
    ];

    def typeConditions = types.collect { "node.type = '${it}'" }.join(" OR ");
    def query = """
        SELECT * FROM [nt:unstructured] AS node WHERE ISDESCENDANTNODE([${homePage.getPath()}])
        and (node.[sling:resourceType]='${resourceType}')
        and (${typeConditions})
    """
    sql2Query(query).each( node -> {
        properties.each((key, value) -> {
            def translatedValue = translate_SHOWCASE_PANEL(value, getLocale(node));
            println """set ${key}:${translatedValue} to ${node.getPath()}"""
            node.setProperty(key, translatedValue)
        })
    })
}


getHomePages().each( homePage -> {
    handleShowcasePanel(homePage);

    if(DRY_RUN) {
        session.refresh(false);
    } else {
        save();
    }
})