import groovy.transform.Field

@Field DRY_RUN = true

def getHomePages() {
    return sql2Query("""
        SELECT * FROM [nt:unstructured] AS node
        WHERE ISDESCENDANTNODE('/content/dhl')
        AND node.[cq:template] = '/conf/dhl/settings/wcm/templates/home-page'
    """).stream().map{ it.getParent() };
}

@Field DICTIONARY_PARALLAX_SECTION = [
        "en-IE": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "de": ["Wooden Guitar": "Gitarre aus Holz", "Chello": "Chello", "Man": "Mann", "Brass Chello": "Chello aus Messing", "Coffee": "Kaffee", "Stationary": "Stationär", "Laptop": "Laptop", "Coffee Brew": "Kaffee-Gebräu", "Man painting on a wall": "Mann malt an einer Wand", "Phone": "Telefon", "Bed": "Bett", "Dry Leaves": "Trockene Blätter", "Pillow": "Kissen", "Music": "Musik", "Speaker": "Lautsprecher", "Gold watch": "Goldene Uhr", "Headphones": "Kopfhörer", "Grey watch": "Graue Uhr", "Desk watch": "Schreibtischuhr", "Bullitt": "Bullitt", "Space": "Raum", "Earring": "Ohrring", "Tux": "Smoking", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "Weiße Apple Smartwatch", "Glasses": "Brille", "Garmin Sports Watch": "Garmin Sportuhr", "Tea": "Tee", "Wood color watch": "Uhr in Holzfarbe", "Watch in hand": "Uhr in der Hand", "Shop": "Laden", "Coat": "Mantel", "Zara": "Zara", "Catwalk": "Laufsteg", "Fashion Bag": "Modetasche", "Girl": "Mädchen", "Yoghurt": "Joghurt", "Bowl": "Schüssel", "Spices": "Gewürze", "Bullit in Space": "Bullit im All", "Bottle": "Flasche", "Chemical": "Chemisch", "Beach": "Strand", "Sea": "Meer", "Paper": "Papier", "Pencil": "Bleistift", "Highlighter": "Textmarker", "Calendar": "Kalender", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "hi": ["Wooden Guitar": "लकड़ी का गिटार", "Chello": "चेलो", "Man": "आदमी", "Brass Chello": "पीतल चेलो", "Coffee": "प्‍याला-भर कॉफ़ी", "Stationary": "गतिहीन", "Laptop": "लैपटॉप", "Coffee Brew": "कॉफी काढ़ा", "Man painting on a wall": "दीवार पर पेंटिंग करता आदमी", "Phone": "फ़ोन", "Bed": "बिस्तर", "Dry Leaves": "सूखी पत्तियां", "Pillow": "सिरहाना", "Music": "राग", "Speaker": "वक्ता", "Gold watch": "सोने की घड़ी", "Headphones": "हेडफ़ोन", "Grey watch": "ग्रे घड़ी", "Desk watch": "डेस्क घड़ी", "Bullitt": "बुलिट", "Space": "अन्तरिक्ष", "Earring": "कान की बाली", "Tux": "टक्स", "Ring": "वलय", "Hand": "हाथ", "White Apple Smart Watch": "व्हाइट एप्पल स्मार्ट वॉच", "Glasses": "चश्‍मा", "Garmin Sports Watch": "गार्मिन स्पोर्ट्स वॉच", "Tea": "भोजन", "Wood color watch": "लकड़ी के रंग की घड़ी", "Watch in hand": "हाथ में घड़ी", "Shop": "ख़रीदारी करना", "Coat": "लेप लगाना", "Zara": "जरा", "Catwalk": "कैटवॉक", "Fashion Bag": "फैशन बैग", "Girl": "लड़की", "Yoghurt": "दधि", "Bowl": "गेंदबाज़ी करना", "Spices": "मसाले", "Bullit in Space": "अंतरिक्ष में बुलिट", "Bottle": "बोतलबंद करना", "Chemical": "रसायन", "Beach": "पुलिन", "Sea": "समुद्र", "Paper": "शोधपत्र", "Pencil": "पेंसिल", "Highlighter": "हाईलाइटर", "Calendar": "कैलेंडर", "Bullitt-1": "Bullitt-1 (बुलिट-1)", "Bullitt-2": "Bullitt-2 (बुलिट-2)"],
        "en-US": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "pt": ["Wooden Guitar": "Guitarra de madeira", "Chello": "Chello", "Man": "Homem", "Brass Chello": "Chello de latão", "Coffee": "Café", "Stationary": "Estacionário", "Laptop": "Computador portátil", "Coffee Brew": "Café Brew", "Man painting on a wall": "Homem pintando em uma parede", "Phone": "Telefone", "Bed": "Cama", "Dry Leaves": "Folhas Secas", "Pillow": "Almofada", "Music": "Música", "Speaker": "Orador", "Gold watch": "Relógio de ouro", "Headphones": "Auscultadores", "Grey watch": "Relógio cinza", "Desk watch": "Relógio de mesa", "Bullitt": "Bullitt", "Space": "Espaço", "Earring": "Brinco", "Tux": "Smoking", "Ring": "Anel", "Hand": "Mão", "White Apple Smart Watch": "Relógio inteligente Apple branco", "Glasses": "Óculos", "Garmin Sports Watch": "Relógio esportivo Garmin", "Tea": "Chá", "Wood color watch": "Relógio de cor de madeira", "Watch in hand": "Relógio na mão", "Shop": "Loja", "Coat": "Casaco", "Zara": "Zara", "Catwalk": "Passarela", "Fashion Bag": "Bolsa de moda", "Girl": "Garota", "Yoghurt": "Iogurte", "Bowl": "Tigela", "Spices": "Especiarias", "Bullit in Space": "Bullit no espaço", "Bottle": "Garrafa", "Chemical": "Químico", "Beach": "Praia", "Sea": "Mar", "Paper": "Papel", "Pencil": "Lápis", "Highlighter": "Marcador", "Calendar": "Calendário", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-MM": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-IN": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-ZA": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "hu": ["Wooden Guitar": "Fa gitár", "Chello": "Chello", "Man": "Férfi", "Brass Chello": "Rézfúvós Chello", "Coffee": "Kávé", "Stationary": "Mozdulatlan", "Laptop": "Laptop", "Coffee Brew": "Kávéfőzés", "Man painting on a wall": "Férfi fest a falra", "Phone": "Telefon", "Bed": "Ágy", "Dry Leaves": "Száraz levelek", "Pillow": "Párna", "Music": "Zene", "Speaker": "Beszélő", "Gold watch": "Arany óra", "Headphones": "Fejhallgató", "Grey watch": "Szürke óra", "Desk watch": "Asztali óra", "Bullitt": "Bullitt", "Space": "Tér", "Earring": "Fülbevaló", "Tux": "Tux", "Ring": "Gyűrű", "Hand": "Kéz", "White Apple Smart Watch": "Fehér Apple Smart Watch", "Glasses": "Szemüveg", "Garmin Sports Watch": "Garmin sportóra", "Tea": "Tea", "Wood color watch": "Fa színű óra", "Watch in hand": "Óra a kezében", "Shop": "Bolt", "Coat": "Kabát", "Zara": "Zara", "Catwalk": "Tetőjáró", "Fashion Bag": "Divatos táska", "Girl": "Lány", "Yoghurt": "Joghurt", "Bowl": "Tál", "Spices": "Fűszerek", "Bullit in Space": "Bullit az űrben", "Bottle": "Üveg", "Chemical": "Kémiai", "Beach": "Strand", "Sea": "Tenger", "Paper": "Papír", "Pencil": "Ceruza", "Highlighter": "Kiemelő", "Calendar": "Naptár", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "nl-BE": ["Wooden Guitar": "Houten gitaar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Messing Chello", "Coffee": "Koffie", "Stationary": "Stationair", "Laptop": "Laptop", "Coffee Brew": "Koffie brouwen", "Man painting on a wall": "Mens het schilderen op een muur", "Phone": "Telefoon", "Bed": "Bed", "Dry Leaves": "Droge bladeren", "Pillow": "Kussen", "Music": "Muziek", "Speaker": "Luidspreker", "Gold watch": "Gouden horloge", "Headphones": "Hoofdtelefoon", "Grey watch": "Grijs horloge", "Desk watch": "Bureau horloge", "Bullitt": "Bullitt", "Space": "Ruimte", "Earring": "Oorbel", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "Witte Apple Smart Watch", "Glasses": "Bril", "Garmin Sports Watch": "Garmin sporthorloge", "Tea": "Thee", "Wood color watch": "Hout kleur horloge", "Watch in hand": "Horloge in de hand", "Shop": "Winkel", "Coat": "Jas", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Mode tas", "Girl": "Meisje", "Yoghurt": "Yoghurt", "Bowl": "Kom", "Spices": "Specerijen", "Bullit in Space": "Bullit in de ruimte", "Bottle": "Fles", "Chemical": "Chemisch", "Beach": "Strand", "Sea": "Zee", "Paper": "Papier", "Pencil": "Potlood", "Highlighter": "Markeerstift", "Calendar": "Kalender", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "zh-CN": ["Wooden Guitar": "木制吉他", "Chello": "切罗", "Man": "男人", "Brass Chello": "黄铜 Chello", "Coffee": "咖啡", "Stationary": "固定", "Laptop": "笔记本", "Coffee Brew": "咖啡冲泡", "Man painting on a wall": "男人在墙上画画", "Phone": "电话", "Bed": "床", "Dry Leaves": "干叶", "Pillow": "枕头", "Music": "音乐", "Speaker": "议长", "Gold watch": "金表", "Headphones": "耳机", "Grey watch": "灰色手表", "Desk watch": "台表", "Bullitt": "布利特", "Space": "空间", "Earring": "耳环", "Tux": "礼服", "Ring": "戒指", "Hand": "手", "White Apple Smart Watch": "白色 Apple 智能手表", "Glasses": "眼镜", "Garmin Sports Watch": "Garmin 运动手表", "Tea": "茶", "Wood color watch": "木色手表", "Watch in hand": "手表在手", "Shop": "店", "Coat": "外套", "Zara": "扎拉", "Catwalk": "台步", "Fashion Bag": "时尚包", "Girl": "女孩", "Yoghurt": "酸奶", "Bowl": "碗", "Spices": "香料", "Bullit in Space": "Bullit 在太空", "Bottle": "瓶", "Chemical": "化学的", "Beach": "海滩", "Sea": "海", "Paper": "纸", "Pencil": "铅笔", "Highlighter": "荧光笔", "Calendar": "日历", "Bullitt-1": "Bullitt-1 （布利特-1）", "Bullitt-2": "Bullitt-2 （布利特-2）"],
        "en-IT": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "el-GR": ["Wooden Guitar": "Ξύλινη κιθάρα", "Chello": "Τσέλο", "Man": "Άνδρας", "Brass Chello": "Τσέλο ορείχαλκου", "Coffee": "Καφές", "Stationary": "Στάσιμος", "Laptop": "Φορητός υπολογιστής", "Coffee Brew": "Παρασκευή καφέ", "Man painting on a wall": "Άνδρας ζωγραφίζει σε έναν τοίχο", "Phone": "Τηλέφωνο", "Bed": "Κρεβάτι", "Dry Leaves": "Ξηρά φύλλα", "Pillow": "Μαξιλάρι", "Music": "Μουσική", "Speaker": "Μεγάφωνο", "Gold watch": "Χρυσό ρολόι", "Headphones": "Ακουστικά", "Grey watch": "Γκρι ρολόι", "Desk watch": "Ρολόι γραφείου", "Bullitt": "Μπούλιτ", "Space": "Χώρος", "Earring": "Σκουλαρίκι", "Tux": "Tux", "Ring": "Δαχτυλίδι", "Hand": "Χέρι", "White Apple Smart Watch": "Λευκό έξυπνο ρολόι Apple", "Glasses": "Γυαλιά", "Garmin Sports Watch": "Αθλητικό ρολόι Garmin", "Tea": "Τσάι", "Wood color watch": "Ρολόι χρώματος ξύλου", "Watch in hand": "Ρολόι στο χέρι", "Shop": "Κατάστημα", "Coat": "Σακάκι", "Zara": "Ζάρα", "Catwalk": "Πασαρέλα", "Fashion Bag": "Τσάντα μόδας", "Girl": "Κορίτσι", "Yoghurt": "Γιαούρτι", "Bowl": "Κύπελλο", "Spices": "Μπαχαρικά", "Bullit in Space": "Bullit στο διάστημα", "Bottle": "Μπουκάλι", "Chemical": "Χημικός", "Beach": "Παραλία", "Sea": "Θάλασσα", "Paper": "Χαρτί", "Pencil": "Μολύβι", "Highlighter": "Highlighter", "Calendar": "Ημερολόγιο", "Bullitt-1": "Μπούλιτ-1", "Bullitt-2": "Μπούλιτ-2"],
        "en-MY": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-ES": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-AT": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-AU": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "id": ["Wooden Guitar": "Gitar Kayu", "Chello": "Chello", "Man": "Laki-laki", "Brass Chello": "Chello Kuningan", "Coffee": "Kopi", "Stationary": "Stasioner", "Laptop": "Komputer jinjing", "Coffee Brew": "Minuman Kopi", "Man painting on a wall": "Pria melukis di dinding", "Phone": "Ponsel", "Bed": "Tempat tidur", "Dry Leaves": "Daun kering", "Pillow": "Bantal", "Music": "Musik", "Speaker": "Pembicara", "Gold watch": "Jam tangan emas", "Headphones": "Headphone", "Grey watch": "Jam tangan abu-abu", "Desk watch": "Jam tangan meja", "Bullitt": "Bullitt", "Space": "Antariksa", "Earring": "Anting-anting", "Tux": "Tux", "Ring": "Cincin", "Hand": "Tangan", "White Apple Smart Watch": "Jam Tangan Pintar Apple Putih", "Glasses": "Kacamata", "Garmin Sports Watch": "Jam Tangan Olahraga Garmin", "Tea": "Teh", "Wood color watch": "Jam tangan warna kayu", "Watch in hand": "Jam tangan di tangan", "Shop": "Toko", "Coat": "Jas", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Tas Fashion", "Girl": "Gadis", "Yoghurt": "Yoghurt", "Bowl": "Mangkok", "Spices": "Bumbu", "Bullit in Space": "Bullit di Luar Angkasa", "Bottle": "Botol", "Chemical": "Kimiawi", "Beach": "Pantai", "Sea": "Laut", "Paper": "Kertas", "Pencil": "Pensil", "Highlighter": "Penyorot", "Calendar": "Kalender", "Bullitt-1": "Bullitt-1 (Bahasa Inggris)", "Bullitt-2": "Bullitt-2 (Bahasa Inggris)"],
        "en-NG": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-VN": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "de-CH": ["Wooden Guitar": "Gitarre aus Holz", "Chello": "Chello", "Man": "Mann", "Brass Chello": "Chello aus Messing", "Coffee": "Kaffee", "Stationary": "Stationär", "Laptop": "Laptop", "Coffee Brew": "Kaffee-Gebräu", "Man painting on a wall": "Mann malt an einer Wand", "Phone": "Telefon", "Bed": "Bett", "Dry Leaves": "Trockene Blätter", "Pillow": "Kissen", "Music": "Musik", "Speaker": "Lautsprecher", "Gold watch": "Goldene Uhr", "Headphones": "Kopfhörer", "Grey watch": "Graue Uhr", "Desk watch": "Schreibtischuhr", "Bullitt": "Bullitt", "Space": "Raum", "Earring": "Ohrring", "Tux": "Smoking", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "Weiße Apple Smartwatch", "Glasses": "Brille", "Garmin Sports Watch": "Garmin Sportuhr", "Tea": "Tee", "Wood color watch": "Uhr in Holzfarbe", "Watch in hand": "Uhr in der Hand", "Shop": "Laden", "Coat": "Mantel", "Zara": "Zara", "Catwalk": "Laufsteg", "Fashion Bag": "Modetasche", "Girl": "Mädchen", "Yoghurt": "Joghurt", "Bowl": "Schüssel", "Spices": "Gewürze", "Bullit in Space": "Bullit im All", "Bottle": "Flasche", "Chemical": "Chemisch", "Beach": "Strand", "Sea": "Meer", "Paper": "Papier", "Pencil": "Bleistift", "Highlighter": "Textmarker", "Calendar": "Kalender", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "ms": ["Wooden Guitar": "Gitar Kayu", "Chello": "Chello", "Man": "Lelaki", "Brass Chello": "Tembaga Chello", "Coffee": "Kopi", "Stationary": "Pegun", "Laptop": "Komputer riba", "Coffee Brew": "Minuman Kopi", "Man painting on a wall": "Lelaki melukis di dinding", "Phone": "Telefon", "Bed": "Katil", "Dry Leaves": "Daun kering", "Pillow": "Bantal", "Music": "Muzik", "Speaker": "Penceramah", "Gold watch": "Jam tangan emas", "Headphones": "Fon kepala", "Grey watch": "Jam tangan kelabu", "Desk watch": "Jam tangan meja", "Bullitt": "Bullitt", "Space": "Ruang", "Earring": "Anting-anting", "Tux": "Tux", "Ring": "Cincin", "Hand": "Tangan", "White Apple Smart Watch": "Jam Tangan Pintar Apple Putih", "Glasses": "Gelas", "Garmin Sports Watch": "Jam Tangan Sukan Garmin", "Tea": "Teh", "Wood color watch": "Jam tangan warna kayu", "Watch in hand": "Jam tangan di tangan", "Shop": "Kedai", "Coat": "Kot", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Beg Fesyen", "Girl": "Gadis", "Yoghurt": "Yogurt", "Bowl": "Mangkuk", "Spices": "Rempah", "Bullit in Space": "Bullit di angkasa lepas", "Bottle": "Botol", "Chemical": "Kimia", "Beach": "Pantai", "Sea": "Laut", "Paper": "Kertas", "Pencil": "Pensil", "Highlighter": "Penyerlah", "Calendar": "Kalendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-BD": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "el": ["Wooden Guitar": "Ξύλινη κιθάρα", "Chello": "Τσέλο", "Man": "Άνδρας", "Brass Chello": "Τσέλο ορείχαλκου", "Coffee": "Καφές", "Stationary": "Στάσιμος", "Laptop": "Φορητός υπολογιστής", "Coffee Brew": "Παρασκευή καφέ", "Man painting on a wall": "Άνδρας ζωγραφίζει σε έναν τοίχο", "Phone": "Τηλέφωνο", "Bed": "Κρεβάτι", "Dry Leaves": "Ξηρά φύλλα", "Pillow": "Μαξιλάρι", "Music": "Μουσική", "Speaker": "Μεγάφωνο", "Gold watch": "Χρυσό ρολόι", "Headphones": "Ακουστικά", "Grey watch": "Γκρι ρολόι", "Desk watch": "Ρολόι γραφείου", "Bullitt": "Μπούλιτ", "Space": "Χώρος", "Earring": "Σκουλαρίκι", "Tux": "Tux", "Ring": "Δαχτυλίδι", "Hand": "Χέρι", "White Apple Smart Watch": "Λευκό έξυπνο ρολόι Apple", "Glasses": "Γυαλιά", "Garmin Sports Watch": "Αθλητικό ρολόι Garmin", "Tea": "Τσάι", "Wood color watch": "Ρολόι χρώματος ξύλου", "Watch in hand": "Ρολόι στο χέρι", "Shop": "Κατάστημα", "Coat": "Σακάκι", "Zara": "Ζάρα", "Catwalk": "Πασαρέλα", "Fashion Bag": "Τσάντα μόδας", "Girl": "Κορίτσι", "Yoghurt": "Γιαούρτι", "Bowl": "Κύπελλο", "Spices": "Μπαχαρικά", "Bullit in Space": "Bullit στο διάστημα", "Bottle": "Μπουκάλι", "Chemical": "Χημικός", "Beach": "Παραλία", "Sea": "Θάλασσα", "Paper": "Χαρτί", "Pencil": "Μολύβι", "Highlighter": "Highlighter", "Calendar": "Ημερολόγιο", "Bullitt-1": "Μπούλιτ-1", "Bullitt-2": "Μπούλιτ-2"],
        "en": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "it": ["Wooden Guitar": "Chitarra in legno", "Chello": "Chello", "Man": "Uomo", "Brass Chello": "Ottone Chello", "Coffee": "Caffè", "Stationary": "Stazionario", "Laptop": "Portatile", "Coffee Brew": "Caffè Brew", "Man painting on a wall": "Uomo che dipinge su un muro", "Phone": "Telefono", "Bed": "Letto", "Dry Leaves": "Foglie secche", "Pillow": "Guanciale", "Music": "Musica", "Speaker": "Altoparlante", "Gold watch": "Orologio d'oro", "Headphones": "Cuffia", "Grey watch": "Orologio grigio", "Desk watch": "Orologio da tavolo", "Bullitt": "Bullitt", "Space": "Spazio", "Earring": "Orecchino", "Tux": "Tux", "Ring": "Anello", "Hand": "Mano", "White Apple Smart Watch": "Orologio intelligente Apple bianco", "Glasses": "Occhiali", "Garmin Sports Watch": "Orologio sportivo Garmin", "Tea": "Tè", "Wood color watch": "Orologio color legno", "Watch in hand": "Orologio alla mano", "Shop": "Negozio", "Coat": "Cappotto", "Zara": "Zara", "Catwalk": "Passerella", "Fashion Bag": "Borsa alla moda", "Girl": "Ragazza", "Yoghurt": "Yogurt", "Bowl": "Ciotola", "Spices": "Spezie", "Bullit in Space": "Bullit nello spazio", "Bottle": "Bottiglia", "Chemical": "Chimico", "Beach": "Spiaggia", "Sea": "Mare", "Paper": "Carta", "Pencil": "Matita", "Highlighter": "Evidenziatore", "Calendar": "Calendario", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "es": ["Wooden Guitar": "Guitarra de madera", "Chello": "Chello", "Man": "Hombre", "Brass Chello": "Chello de latón", "Coffee": "Café", "Stationary": "Estacionario", "Laptop": "Portátil", "Coffee Brew": "Preparación de café", "Man painting on a wall": "Hombre pintando en una pared", "Phone": "Teléfono", "Bed": "Cama", "Dry Leaves": "Hojas secas", "Pillow": "Almohada", "Music": "Música", "Speaker": "Orador", "Gold watch": "Reloj de oro", "Headphones": "Auriculares", "Grey watch": "Reloj gris", "Desk watch": "Reloj de escritorio", "Bullitt": "Bullitt", "Space": "Espacio", "Earring": "Arete", "Tux": "Tux", "Ring": "Anillo", "Hand": "Mano", "White Apple Smart Watch": "Reloj inteligente Apple blanco", "Glasses": "Gafas", "Garmin Sports Watch": "Reloj deportivo Garmin", "Tea": "Té", "Wood color watch": "Reloj color madera", "Watch in hand": "Reloj en mano", "Shop": "Tienda", "Coat": "Abrigo", "Zara": "Zara", "Catwalk": "Pasarela", "Fashion Bag": "Bolso de moda", "Girl": "Muchacha", "Yoghurt": "Yogur", "Bowl": "Tazón", "Spices": "Especias", "Bullit in Space": "Bullit en el espacio", "Bottle": "Botella", "Chemical": "Químico", "Beach": "Playa", "Sea": "Mar", "Paper": "Papel", "Pencil": "Lápiz", "Highlighter": "Iluminador", "Calendar": "Calendario", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "zh": ["Wooden Guitar": "木制吉他", "Chello": "切罗", "Man": "男人", "Brass Chello": "黄铜 Chello", "Coffee": "咖啡", "Stationary": "固定", "Laptop": "笔记本", "Coffee Brew": "咖啡冲泡", "Man painting on a wall": "男人在墙上画画", "Phone": "电话", "Bed": "床", "Dry Leaves": "干叶", "Pillow": "枕头", "Music": "音乐", "Speaker": "议长", "Gold watch": "金表", "Headphones": "耳机", "Grey watch": "灰色手表", "Desk watch": "台表", "Bullitt": "布利特", "Space": "空间", "Earring": "耳环", "Tux": "礼服", "Ring": "戒指", "Hand": "手", "White Apple Smart Watch": "白色 Apple 智能手表", "Glasses": "眼镜", "Garmin Sports Watch": "Garmin 运动手表", "Tea": "茶", "Wood color watch": "木色手表", "Watch in hand": "手表在手", "Shop": "店", "Coat": "外套", "Zara": "扎拉", "Catwalk": "台步", "Fashion Bag": "时尚包", "Girl": "女孩", "Yoghurt": "酸奶", "Bowl": "碗", "Spices": "香料", "Bullit in Space": "Bullit 在太空", "Bottle": "瓶", "Chemical": "化学的", "Beach": "海滩", "Sea": "海", "Paper": "纸", "Pencil": "铅笔", "Highlighter": "荧光笔", "Calendar": "日历", "Bullitt-1": "Bullitt-1 （布利特-1）", "Bullitt-2": "Bullitt-2 （布利特-2）"],
        "fr-CA": ["Wooden Guitar": "Guitare en bois", "Chello": "Chello", "Man": "Homme", "Brass Chello": "Chello en laiton", "Coffee": "Café", "Stationary": "Stationnaire", "Laptop": "Ordinateur portable", "Coffee Brew": "Infusion de café", "Man painting on a wall": "Homme peignant sur un mur", "Phone": "Téléphone", "Bed": "Lit", "Dry Leaves": "Feuilles sèches", "Pillow": "Oreiller", "Music": "Musique", "Speaker": "Conférencier", "Gold watch": "Montre en or", "Headphones": "Casque d’écoute", "Grey watch": "Montre grise", "Desk watch": "Surveillance de bureau", "Bullitt": "Bullitt", "Space": "Espace", "Earring": "Boucle d’oreille", "Tux": "Smoking", "Ring": "Anneau", "Hand": "Main", "White Apple Smart Watch": "Montre intelligente Apple blanche", "Glasses": "Lunettes", "Garmin Sports Watch": "Montre de sport Garmin", "Tea": "Thé", "Wood color watch": "Montre couleur bois", "Watch in hand": "Montre à la main", "Shop": "Magasiner", "Coat": "Manteau", "Zara": "Zara", "Catwalk": "Défilé", "Fashion Bag": "Sac de mode", "Girl": "Fille", "Yoghurt": "Yogourt", "Bowl": "Bol", "Spices": "Épices", "Bullit in Space": "Bullit dans l’espace", "Bottle": "Bouteille", "Chemical": "Chimique", "Beach": "Plage", "Sea": "Mer", "Paper": "Papier", "Pencil": "Crayon", "Highlighter": "Surligneur", "Calendar": "Calendrier", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-NZ": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "vi": ["Wooden Guitar": "Guitar gỗ", "Chello": "Chello", "Man": "Đàn ông", "Brass Chello": "Đồng thau Chello", "Coffee": "Cà phê", "Stationary": "Văn phòng phẩm", "Laptop": "Máy tính xách tay", "Coffee Brew": "Pha cà phê", "Man painting on a wall": "Người đàn ông vẽ trên tường", "Phone": "Điện thoại", "Bed": "Giường", "Dry Leaves": "Lá khô", "Pillow": "Gối", "Music": "Âm nhạc", "Speaker": "Loa", "Gold watch": "Đồng hồ vàng", "Headphones": "Tai nghe", "Grey watch": "Đồng hồ màu xám", "Desk watch": "Đồng hồ bàn", "Bullitt": "Bullitt", "Space": "Không gian", "Earring": "Hoa tai", "Tux": "Tux", "Ring": "Nhẫn", "Hand": "Tay", "White Apple Smart Watch": "Đồng hồ thông minh Apple màu trắng", "Glasses": "Kính", "Garmin Sports Watch": "Đồng hồ thể thao Garmin", "Tea": "Trà", "Wood color watch": "Đồng hồ màu gỗ", "Watch in hand": "Đồng hồ trong tay", "Shop": "Cửa hàng", "Coat": "Áo", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Túi thời trang", "Girl": "Cô bé", "Yoghurt": "Sữa chua", "Bowl": "Bát", "Spices": "Gia", "Bullit in Space": "Bullit trong không gian", "Bottle": "Chai", "Chemical": "Hóa chất", "Beach": "Bãi biển", "Sea": "Biển", "Paper": "Giấy", "Pencil": "Bút chì", "Highlighter": "Bút đánh dấu", "Calendar": "Lịch", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2 (Tội lỗi-2)"],
        "fr-BE": ["Wooden Guitar": "Guitare en bois", "Chello": "Chello", "Man": "Homme", "Brass Chello": "Chello en laiton", "Coffee": "Café", "Stationary": "Stationnaire", "Laptop": "Ordinateur portable", "Coffee Brew": "Infusion de café", "Man painting on a wall": "Homme peignant sur un mur", "Phone": "Téléphone", "Bed": "Lit", "Dry Leaves": "Feuilles sèches", "Pillow": "Oreiller", "Music": "Musique", "Speaker": "Orateur", "Gold watch": "Montre en or", "Headphones": "Casque", "Grey watch": "Montre grise", "Desk watch": "Montre de bureau", "Bullitt": "Bullitt", "Space": "Espace", "Earring": "Boucle d’oreille", "Tux": "Tux", "Ring": "Bague", "Hand": "Main", "White Apple Smart Watch": "Montre intelligente Apple blanche", "Glasses": "Lunettes", "Garmin Sports Watch": "Montre de sport Garmin", "Tea": "Thé", "Wood color watch": "Montre couleur bois", "Watch in hand": "Montre en main", "Shop": "Boutique", "Coat": "Manteau", "Zara": "Zara", "Catwalk": "Passerelle", "Fashion Bag": "Sac de mode", "Girl": "Fille", "Yoghurt": "Yaourt", "Bowl": "Bol", "Spices": "Épices", "Bullit in Space": "Bullit dans l’espace", "Bottle": "Bouteille", "Chemical": "Chimique", "Beach": "Plage", "Sea": "Mer", "Paper": "Papier", "Pencil": "Crayon", "Highlighter": "Surligneur", "Calendar": "Calendrier", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "ja": ["Wooden Guitar": "木製ギター", "Chello": "チェロ", "Man": "男", "Brass Chello": "ブラスチェロ", "Coffee": "コーヒー", "Stationary": "固定された", "Laptop": "ラップトップ", "Coffee Brew": "コーヒーブリュー", "Man painting on a wall": "壁に絵を描く男", "Phone": "電話", "Bed": "ベッド", "Dry Leaves": "ドライリーフ", "Pillow": "枕", "Music": "音楽", "Speaker": "話者", "Gold watch": "ゴールドウォッチ", "Headphones": "ヘッドフォン", "Grey watch": "グレーウォッチ", "Desk watch": "デスクウォッチ", "Bullitt": "ブリット", "Space": "間", "Earring": "イヤリング", "Tux": "タキシード", "Ring": "指輪", "Hand": "手", "White Apple Smart Watch": "ホワイトアップルスマートウォッチ", "Glasses": "眼鏡", "Garmin Sports Watch": "ガーミンスポーツウォッチ", "Tea": "茶", "Wood color watch": "ウッドカラーウォッチ", "Watch in hand": "時計を手元に", "Shop": "店", "Coat": "上着", "Zara": "ザラ", "Catwalk": "キャットウォーク", "Fashion Bag": "ファッションバッグ", "Girl": "女の子", "Yoghurt": "ヨーグルト", "Bowl": "鉢", "Spices": "スパイス", "Bullit in Space": "宇宙のブリット", "Bottle": "瓶", "Chemical": "ケミカル", "Beach": "浜", "Sea": "海", "Paper": "紙", "Pencil": "鉛筆", "Highlighter": "蛍光ペン", "Calendar": "暦", "Bullitt-1": "ブリット-1", "Bullitt-2": "ブリット-2"],
        "en-SG": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "it-CH": ["Wooden Guitar": "Chitarra in legno", "Chello": "Chello", "Man": "Uomo", "Brass Chello": "Ottone Chello", "Coffee": "Caffè", "Stationary": "Stazionario", "Laptop": "Portatile", "Coffee Brew": "Caffè Brew", "Man painting on a wall": "Uomo che dipinge su un muro", "Phone": "Telefono", "Bed": "Letto", "Dry Leaves": "Foglie secche", "Pillow": "Guanciale", "Music": "Musica", "Speaker": "Altoparlante", "Gold watch": "Orologio d'oro", "Headphones": "Cuffia", "Grey watch": "Orologio grigio", "Desk watch": "Orologio da tavolo", "Bullitt": "Bullitt", "Space": "Spazio", "Earring": "Orecchino", "Tux": "Tux", "Ring": "Anello", "Hand": "Mano", "White Apple Smart Watch": "Orologio intelligente Apple bianco", "Glasses": "Occhiali", "Garmin Sports Watch": "Orologio sportivo Garmin", "Tea": "Tè", "Wood color watch": "Orologio color legno", "Watch in hand": "Orologio alla mano", "Shop": "Negozio", "Coat": "Cappotto", "Zara": "Zara", "Catwalk": "Passerella", "Fashion Bag": "Borsa alla moda", "Girl": "Ragazza", "Yoghurt": "Yogurt", "Bowl": "Ciotola", "Spices": "Spezie", "Bullit in Space": "Bullit nello spazio", "Bottle": "Bottiglia", "Chemical": "Chimico", "Beach": "Spiaggia", "Sea": "Mare", "Paper": "Carta", "Pencil": "Matita", "Highlighter": "Evidenziatore", "Calendar": "Calendario", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "fr-FR": ["Wooden Guitar": "Guitare en bois", "Chello": "Chello", "Man": "Homme", "Brass Chello": "Chello en laiton", "Coffee": "Café", "Stationary": "Stationnaire", "Laptop": "Ordinateur portable", "Coffee Brew": "Infusion de café", "Man painting on a wall": "Homme peignant sur un mur", "Phone": "Téléphone", "Bed": "Lit", "Dry Leaves": "Feuilles sèches", "Pillow": "Oreiller", "Music": "Musique", "Speaker": "Orateur", "Gold watch": "Montre en or", "Headphones": "Casque", "Grey watch": "Montre grise", "Desk watch": "Montre de bureau", "Bullitt": "Bullitt", "Space": "Espace", "Earring": "Boucle d’oreille", "Tux": "Tux", "Ring": "Bague", "Hand": "Main", "White Apple Smart Watch": "Montre intelligente Apple blanche", "Glasses": "Lunettes", "Garmin Sports Watch": "Montre de sport Garmin", "Tea": "Thé", "Wood color watch": "Montre couleur bois", "Watch in hand": "Montre en main", "Shop": "Boutique", "Coat": "Manteau", "Zara": "Zara", "Catwalk": "Passerelle", "Fashion Bag": "Sac de mode", "Girl": "Fille", "Yoghurt": "Yaourt", "Bowl": "Bol", "Spices": "Épices", "Bullit in Space": "Bullit dans l’espace", "Bottle": "Bouteille", "Chemical": "Chimique", "Beach": "Plage", "Sea": "Mer", "Paper": "Papier", "Pencil": "Crayon", "Highlighter": "Surligneur", "Calendar": "Calendrier", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "vi-VN": ["Wooden Guitar": "Guitar gỗ", "Chello": "Chello", "Man": "Đàn ông", "Brass Chello": "Đồng thau Chello", "Coffee": "Cà phê", "Stationary": "Văn phòng phẩm", "Laptop": "Máy tính xách tay", "Coffee Brew": "Pha cà phê", "Man painting on a wall": "Người đàn ông vẽ trên tường", "Phone": "Điện thoại", "Bed": "Giường", "Dry Leaves": "Lá khô", "Pillow": "Gối", "Music": "Âm nhạc", "Speaker": "Loa", "Gold watch": "Đồng hồ vàng", "Headphones": "Tai nghe", "Grey watch": "Đồng hồ màu xám", "Desk watch": "Đồng hồ bàn", "Bullitt": "Bullitt", "Space": "Không gian", "Earring": "Hoa tai", "Tux": "Tux", "Ring": "Nhẫn", "Hand": "Tay", "White Apple Smart Watch": "Đồng hồ thông minh Apple màu trắng", "Glasses": "Kính", "Garmin Sports Watch": "Đồng hồ thể thao Garmin", "Tea": "Trà", "Wood color watch": "Đồng hồ màu gỗ", "Watch in hand": "Đồng hồ trong tay", "Shop": "Cửa hàng", "Coat": "Áo", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Túi thời trang", "Girl": "Cô bé", "Yoghurt": "Sữa chua", "Bowl": "Bát", "Spices": "Gia", "Bullit in Space": "Bullit trong không gian", "Bottle": "Chai", "Chemical": "Hóa chất", "Beach": "Bãi biển", "Sea": "Biển", "Paper": "Giấy", "Pencil": "Bút chì", "Highlighter": "Bút đánh dấu", "Calendar": "Lịch", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2 (Tội lỗi-2)"],
        "en-GB": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood colour watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-KE": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-KH": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "bg": ["Wooden Guitar": "Дървена китара", "Chello": "Хело", "Man": "Мъж", "Brass Chello": "Месингово Кело", "Coffee": "Кафе", "Stationary": "Неподвижен", "Laptop": "Лаптоп", "Coffee Brew": "Приготвяне на кафе", "Man painting on a wall": "Мъж рисува на стена", "Phone": "Телефон", "Bed": "Легло", "Dry Leaves": "Сухи листа", "Pillow": "Възглавница", "Music": "Музика", "Speaker": "Говорител", "Gold watch": "Златен часовник", "Headphones": "Слушалки", "Grey watch": "Сив часовник", "Desk watch": "Настолен часовник", "Bullitt": "Булит", "Space": "Простор", "Earring": "Обица", "Tux": "Смокинг", "Ring": "Пръстен", "Hand": "Ръка", "White Apple Smart Watch": "Бял смарт часовник Apple", "Glasses": "Очила", "Garmin Sports Watch": "Спортен часовник Garmin", "Tea": "Чай", "Wood color watch": "Часовник с цвят дърво", "Watch in hand": "Часовник в ръка", "Shop": "Магазин", "Coat": "Палто", "Zara": "Зара", "Catwalk": "Подиум", "Fashion Bag": "Модна чанта", "Girl": "Момиче", "Yoghurt": "Кисело мляко", "Bowl": "Купа", "Spices": "Подправки", "Bullit in Space": "Булит в космоса", "Bottle": "Шише", "Chemical": "Химически", "Beach": "Плаж", "Sea": "Море", "Paper": "Хартия", "Pencil": "Молив", "Highlighter": "Хайлайтър", "Calendar": "Календар", "Bullitt-1": "Булит-1", "Bullitt-2": "Булит-2"],
        "en-CH": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-KR": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "ar-AE": ["Wooden Guitar": "غيتار خشبي", "Chello": "تشيلو", "Man": "رجل", "Brass Chello": "نحاس تشيلو", "Coffee": "قهوة", "Stationary": "ثابت", "Laptop": "لابتوب", "Coffee Brew": "مشروب القهوة", "Man painting on a wall": "رجل يرسم على الحائط", "Phone": "الهاتف", "Bed": "سرير", "Dry Leaves": "أوراق جافة", "Pillow": "مخدة", "Music": "موسيقى", "Speaker": "سماعة", "Gold watch": "ساعة ذهبية", "Headphones": "سماعات الراس", "Grey watch": "ساعة رمادية", "Desk watch": "ساعة مكتبية", "Bullitt": "بوليت", "Space": "فضاء", "Earring": "قرط", "Tux": "توكس", "Ring": "خاتم", "Hand": "يد", "White Apple Smart Watch": "ساعة أبل الذكية البيضاء", "Glasses": "نظارة", "Garmin Sports Watch": "ساعة جارمين الرياضية", "Tea": "شاي", "Wood color watch": "ساعة ملونة الخشب", "Watch in hand": "شاهد في متناول اليد", "Shop": "دكان", "Coat": "معطف", "Zara": "زارا", "Catwalk": "المنصه", "Fashion Bag": "حقيبة أزياء", "Girl": "بنت", "Yoghurt": "لبن", "Bowl": "وعاء", "Spices": "توابل", "Bullit in Space": "الثور في الفضاء", "Bottle": "زجاجة", "Chemical": "كيميائي", "Beach": "شاطئ", "Sea": "بحر", "Paper": "ورق", "Pencil": "قلم", "Highlighter": "هايلايتر", "Calendar": "تقويم", "Bullitt-1": "بوليت -1", "Bullitt-2": "بوليت -2"],
        "fr": ["Wooden Guitar": "Guitare en bois", "Chello": "Chello", "Man": "Homme", "Brass Chello": "Chello en laiton", "Coffee": "Café", "Stationary": "Stationnaire", "Laptop": "Ordinateur portable", "Coffee Brew": "Infusion de café", "Man painting on a wall": "Homme peignant sur un mur", "Phone": "Téléphone", "Bed": "Lit", "Dry Leaves": "Feuilles sèches", "Pillow": "Oreiller", "Music": "Musique", "Speaker": "Orateur", "Gold watch": "Montre en or", "Headphones": "Casque", "Grey watch": "Montre grise", "Desk watch": "Montre de bureau", "Bullitt": "Bullitt", "Space": "Espace", "Earring": "Boucle d’oreille", "Tux": "Tux", "Ring": "Bague", "Hand": "Main", "White Apple Smart Watch": "Montre intelligente Apple blanche", "Glasses": "Lunettes", "Garmin Sports Watch": "Montre de sport Garmin", "Tea": "Thé", "Wood color watch": "Montre couleur bois", "Watch in hand": "Montre en main", "Shop": "Boutique", "Coat": "Manteau", "Zara": "Zara", "Catwalk": "Passerelle", "Fashion Bag": "Sac de mode", "Girl": "Fille", "Yoghurt": "Yaourt", "Bowl": "Bol", "Spices": "Épices", "Bullit in Space": "Bullit dans l’espace", "Bottle": "Bouteille", "Chemical": "Chimique", "Beach": "Plage", "Sea": "Mer", "Paper": "Papier", "Pencil": "Crayon", "Highlighter": "Surligneur", "Calendar": "Calendrier", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-CN": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "de-AT": ["Wooden Guitar": "Gitarre aus Holz", "Chello": "Chello", "Man": "Mann", "Brass Chello": "Chello aus Messing", "Coffee": "Kaffee", "Stationary": "Stationär", "Laptop": "Laptop", "Coffee Brew": "Kaffee-Gebräu", "Man painting on a wall": "Mann malt an einer Wand", "Phone": "Telefon", "Bed": "Bett", "Dry Leaves": "Trockene Blätter", "Pillow": "Kissen", "Music": "Musik", "Speaker": "Lautsprecher", "Gold watch": "Goldene Uhr", "Headphones": "Kopfhörer", "Grey watch": "Graue Uhr", "Desk watch": "Schreibtischuhr", "Bullitt": "Bullitt", "Space": "Raum", "Earring": "Ohrring", "Tux": "Smoking", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "Weiße Apple Smartwatch", "Glasses": "Brille", "Garmin Sports Watch": "Garmin Sportuhr", "Tea": "Tee", "Wood color watch": "Uhr in Holzfarbe", "Watch in hand": "Uhr in der Hand", "Shop": "Laden", "Coat": "Mantel", "Zara": "Zara", "Catwalk": "Laufsteg", "Fashion Bag": "Modetasche", "Girl": "Mädchen", "Yoghurt": "Joghurt", "Bowl": "Schüssel", "Spices": "Gewürze", "Bullit in Space": "Bullit im All", "Bottle": "Flasche", "Chemical": "Chemisch", "Beach": "Strand", "Sea": "Meer", "Paper": "Papier", "Pencil": "Bleistift", "Highlighter": "Textmarker", "Calendar": "Kalender", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "fr-CH": ["Wooden Guitar": "Guitare en bois", "Chello": "Chello", "Man": "Homme", "Brass Chello": "Chello en laiton", "Coffee": "Café", "Stationary": "Stationnaire", "Laptop": "Ordinateur portable", "Coffee Brew": "Infusion de café", "Man painting on a wall": "Homme peignant sur un mur", "Phone": "Téléphone", "Bed": "Lit", "Dry Leaves": "Feuilles sèches", "Pillow": "Oreiller", "Music": "Musique", "Speaker": "Orateur", "Gold watch": "Montre en or", "Headphones": "Casque", "Grey watch": "Montre grise", "Desk watch": "Montre de bureau", "Bullitt": "Bullitt", "Space": "Espace", "Earring": "Boucle d’oreille", "Tux": "Tux", "Ring": "Bague", "Hand": "Main", "White Apple Smart Watch": "Montre intelligente Apple blanche", "Glasses": "Lunettes", "Garmin Sports Watch": "Montre de sport Garmin", "Tea": "Thé", "Wood color watch": "Montre couleur bois", "Watch in hand": "Montre en main", "Shop": "Boutique", "Coat": "Manteau", "Zara": "Zara", "Catwalk": "Passerelle", "Fashion Bag": "Sac de mode", "Girl": "Fille", "Yoghurt": "Yaourt", "Bowl": "Bol", "Spices": "Épices", "Bullit in Space": "Bullit dans l’espace", "Bottle": "Bouteille", "Chemical": "Chimique", "Beach": "Plage", "Sea": "Mer", "Paper": "Papier", "Pencil": "Crayon", "Highlighter": "Surligneur", "Calendar": "Calendrier", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "sk": ["Wooden Guitar": "Drevená gitara", "Chello": "Chello", "Man": "Muž", "Brass Chello": "Mosadz Chello", "Coffee": "Káva", "Stationary": "Stacionárny", "Laptop": "Laptop", "Coffee Brew": "Kávové varenie", "Man painting on a wall": "Muž maľuje na stenu", "Phone": "Telefón", "Bed": "Posteľ", "Dry Leaves": "Suché listy", "Pillow": "Vankúš", "Music": "Hudba", "Speaker": "Reproduktor", "Gold watch": "Zlaté hodinky", "Headphones": "Slúchadlá", "Grey watch": "Sivé hodinky", "Desk watch": "Stolné hodinky", "Bullitt": "Bullitt", "Space": "Priestor", "Earring": "Náušnica", "Tux": "Tux", "Ring": "Prsteň", "Hand": "Ruka", "White Apple Smart Watch": "Biele inteligentné hodinky Apple", "Glasses": "Okuliare", "Garmin Sports Watch": "Športové hodinky Garmin", "Tea": "Čaj", "Wood color watch": "Hodinky vo farbe dreva", "Watch in hand": "Hodinky v ruke", "Shop": "Obchod", "Coat": "Plášť", "Zara": "Zara", "Catwalk": "Móle", "Fashion Bag": "Módna taška", "Girl": "Dievča", "Yoghurt": "Jogurt", "Bowl": "Misa", "Spices": "Korenie", "Bullit in Space": "Bullit vo vesmíre", "Bottle": "Fľaša", "Chemical": "Chemikália", "Beach": "Pláž", "Sea": "More", "Paper": "Papier", "Pencil": "Ceruzka", "Highlighter": "Zvýrazňovač", "Calendar": "Kalendár", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-TH": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-CZ": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "cs-CZ": ["Wooden Guitar": "Dřevěná kytara", "Chello": "Chello", "Man": "Muž", "Brass Chello": "Mosazné Chello", "Coffee": "Káva", "Stationary": "Stacionární", "Laptop": "Notebook", "Coffee Brew": "Vaření kávy", "Man painting on a wall": "Muž malující na zeď", "Phone": "Telefon", "Bed": "Postel", "Dry Leaves": "Suché listí", "Pillow": "Polštář", "Music": "Hudba", "Speaker": "Reproduktor", "Gold watch": "Zlaté hodinky", "Headphones": "Sluchátka", "Grey watch": "Šedé hodinky", "Desk watch": "Stolní hodinky", "Bullitt": "Bullitt", "Space": "Prostor", "Earring": "Náušnice", "Tux": "Smoking", "Ring": "Prsten", "Hand": "Ruka", "White Apple Smart Watch": "Bílé chytré hodinky Apple", "Glasses": "Brýle", "Garmin Sports Watch": "Sportovní hodinky Garmin", "Tea": "Čaj", "Wood color watch": "Hodinky v barvě dřeva", "Watch in hand": "Hodinky v ruce", "Shop": "Obchod", "Coat": "Kabát", "Zara": "Zara", "Catwalk": "Pódium", "Fashion Bag": "Módní taška", "Girl": "Děvče", "Yoghurt": "Jogurt", "Bowl": "Mísa", "Spices": "Koření", "Bullit in Space": "Bullit ve vesmíru", "Bottle": "Láhev", "Chemical": "Chemický", "Beach": "Pláž", "Sea": "Moře", "Paper": "Papír", "Pencil": "Tužka", "Highlighter": "Zvýrazňovač", "Calendar": "Kalendář", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-PH": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-PK": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-LK": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "de-DE": ["Wooden Guitar": "Gitarre aus Holz", "Chello": "Chello", "Man": "Mann", "Brass Chello": "Chello aus Messing", "Coffee": "Kaffee", "Stationary": "Stationär", "Laptop": "Laptop", "Coffee Brew": "Kaffee-Gebräu", "Man painting on a wall": "Mann malt an einer Wand", "Phone": "Telefon", "Bed": "Bett", "Dry Leaves": "Trockene Blätter", "Pillow": "Kissen", "Music": "Musik", "Speaker": "Lautsprecher", "Gold watch": "Goldene Uhr", "Headphones": "Kopfhörer", "Grey watch": "Graue Uhr", "Desk watch": "Schreibtischuhr", "Bullitt": "Bullitt", "Space": "Raum", "Earring": "Ohrring", "Tux": "Smoking", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "Weiße Apple Smartwatch", "Glasses": "Brille", "Garmin Sports Watch": "Garmin Sportuhr", "Tea": "Tee", "Wood color watch": "Uhr in Holzfarbe", "Watch in hand": "Uhr in der Hand", "Shop": "Laden", "Coat": "Mantel", "Zara": "Zara", "Catwalk": "Laufsteg", "Fashion Bag": "Modetasche", "Girl": "Mädchen", "Yoghurt": "Joghurt", "Bowl": "Schüssel", "Spices": "Gewürze", "Bullit in Space": "Bullit im All", "Bottle": "Flasche", "Chemical": "Chemisch", "Beach": "Strand", "Sea": "Meer", "Paper": "Papier", "Pencil": "Bleistift", "Highlighter": "Textmarker", "Calendar": "Kalender", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "ko": ["Wooden Guitar": "나무 기타", "Chello": "첼로", "Man": "남자", "Brass Chello": "브라스 첼로", "Coffee": "커피", "Stationary": "고정된", "Laptop": "랩톱", "Coffee Brew": "커피 브루", "Man painting on a wall": "벽에 그림을 그리는 남자", "Phone": "전화", "Bed": "침대", "Dry Leaves": "마른 잎", "Pillow": "베개", "Music": "음악", "Speaker": "연설자", "Gold watch": "골드 시계", "Headphones": "헤드폰", "Grey watch": "그레이 워치", "Desk watch": "탁상 시계", "Bullitt": "주인공", "Space": "우주", "Earring": "귀고리", "Tux": "턱시도", "Ring": "반지", "Hand": "손", "White Apple Smart Watch": "화이트 애플 스마트 워치", "Glasses": "안경", "Garmin Sports Watch": "Garmin 스포츠 시계", "Tea": "차", "Wood color watch": "우드 컬러 시계", "Watch in hand": "손에 시계", "Shop": "가게", "Coat": "코트", "Zara": "자라", "Catwalk": "패션쇼", "Fashion Bag": "패션 가방", "Girl": "소녀", "Yoghurt": "요구르트", "Bowl": "그릇", "Spices": "향신료", "Bullit in Space": "우주의 불릿", "Bottle": "병", "Chemical": "화학", "Beach": "바닷가", "Sea": "바다", "Paper": "종이", "Pencil": "연필", "Highlighter": "형광펜", "Calendar": "달력", "Bullitt-1": "불릿-1", "Bullitt-2": "불릿-2"],
        "zh-TW": ["Wooden Guitar": "木製吉他", "Chello": "切羅", "Man": "男人", "Brass Chello": "黃銅 Chello", "Coffee": "咖啡", "Stationary": "固定", "Laptop": "筆記本", "Coffee Brew": "咖啡沖泡", "Man painting on a wall": "男人在牆上畫畫", "Phone": "電話", "Bed": "床", "Dry Leaves": "乾葉", "Pillow": "枕頭", "Music": "音樂", "Speaker": "議長", "Gold watch": "金表", "Headphones": "耳機", "Grey watch": "灰色手錶", "Desk watch": "台表", "Bullitt": "布利特", "Space": "空間", "Earring": "耳環", "Tux": "禮服", "Ring": "戒指", "Hand": "手", "White Apple Smart Watch": "白色 Apple 智慧手錶", "Glasses": "眼鏡", "Garmin Sports Watch": "Garmin 運動手錶", "Tea": "茶", "Wood color watch": "木色手錶", "Watch in hand": "手錶在手錶", "Shop": "店", "Coat": "外套", "Zara": "扎拉", "Catwalk": "台步", "Fashion Bag": "時尚包", "Girl": "女孩", "Yoghurt": "優酪乳", "Bowl": "碗", "Spices": "香料", "Bullit in Space": "Bullit 在太空", "Bottle": "瓶", "Chemical": "化學的", "Beach": "海灘", "Sea": "海", "Paper": "紙", "Pencil": "鉛筆", "Highlighter": "螢光筆", "Calendar": "日曆", "Bullitt-1": "Bullitt-1 （布利特-1）", "Bullitt-2": "Bullitt-2 （布利特-2）"],
        "zh-HK": ["Wooden Guitar": "木製結他", "Chello": "切羅", "Man": "男人", "Brass Chello": "黃銅Chello", "Coffee": "咖啡", "Stationary": "固定", "Laptop": "筆記簿", "Coffee Brew": "咖啡沖泡", "Man painting on a wall": "男人喺牆上畫畫", "Phone": "電話", "Bed": "床", "Dry Leaves": "乾葉", "Pillow": "枕頭", "Music": "音樂", "Speaker": "議長", "Gold watch": "金錶", "Headphones": "耳機", "Grey watch": "灰色手錶", "Desk watch": "台錶", "Bullitt": "布利特", "Space": "空間", "Earring": "耳環", "Tux": "禮服", "Ring": "戒指", "Hand": "手", "White Apple Smart Watch": "白色Apple智能手錶", "Glasses": "眼鏡", "Garmin Sports Watch": "Garmin運動手錶", "Tea": "茶", "Wood color watch": "木色手錶", "Watch in hand": "手錶在手", "Shop": "店", "Coat": "外套", "Zara": "扎拉", "Catwalk": "台步", "Fashion Bag": "時尚包", "Girl": "女孩", "Yoghurt": "酸奶", "Bowl": "碗", "Spices": "香料", "Bullit in Space": "Bullit喺太空", "Bottle": "瓶", "Chemical": "化學嘅", "Beach": "海灘", "Sea": "海", "Paper": "紙", "Pencil": "鉛筆", "Highlighter": "熒光筆", "Calendar": "日曆", "Bullitt-1": "Bullitt-1 （布利特-1）", "Bullitt-2": "Bullitt-2 （布利特-2）"],
        "ko-KR": ["Wooden Guitar": "나무 기타", "Chello": "첼로", "Man": "남자", "Brass Chello": "브라스 첼로", "Coffee": "커피", "Stationary": "고정된", "Laptop": "랩톱", "Coffee Brew": "커피 브루", "Man painting on a wall": "벽에 그림을 그리는 남자", "Phone": "전화", "Bed": "침대", "Dry Leaves": "마른 잎", "Pillow": "베개", "Music": "음악", "Speaker": "연설자", "Gold watch": "골드 시계", "Headphones": "헤드폰", "Grey watch": "그레이 워치", "Desk watch": "탁상 시계", "Bullitt": "주인공", "Space": "우주", "Earring": "귀고리", "Tux": "턱시도", "Ring": "반지", "Hand": "손", "White Apple Smart Watch": "화이트 애플 스마트 워치", "Glasses": "안경", "Garmin Sports Watch": "Garmin 스포츠 시계", "Tea": "차", "Wood color watch": "우드 컬러 시계", "Watch in hand": "손에 시계", "Shop": "가게", "Coat": "코트", "Zara": "자라", "Catwalk": "패션쇼", "Fashion Bag": "패션 가방", "Girl": "소녀", "Yoghurt": "요구르트", "Bowl": "그릇", "Spices": "향신료", "Bullit in Space": "우주의 불릿", "Bottle": "병", "Chemical": "화학", "Beach": "바닷가", "Sea": "바다", "Paper": "종이", "Pencil": "연필", "Highlighter": "형광펜", "Calendar": "달력", "Bullitt-1": "불릿-1", "Bullitt-2": "불릿-2"],
        "pt-BR": ["Wooden Guitar": "Guitarra de madeira", "Chello": "Chello", "Man": "Homem", "Brass Chello": "Chello de latão", "Coffee": "Café", "Stationary": "Estacionário", "Laptop": "Computador portátil", "Coffee Brew": "Café Brew", "Man painting on a wall": "Homem pintando em uma parede", "Phone": "Telefone", "Bed": "Cama", "Dry Leaves": "Folhas Secas", "Pillow": "Almofada", "Music": "Música", "Speaker": "Orador", "Gold watch": "Relógio de ouro", "Headphones": "Auscultadores", "Grey watch": "Relógio cinza", "Desk watch": "Relógio de mesa", "Bullitt": "Bullitt", "Space": "Espaço", "Earring": "Brinco", "Tux": "Smoking", "Ring": "Anel", "Hand": "Mão", "White Apple Smart Watch": "Relógio inteligente Apple branco", "Glasses": "Óculos", "Garmin Sports Watch": "Relógio esportivo Garmin", "Tea": "Chá", "Wood color watch": "Relógio de cor de madeira", "Watch in hand": "Relógio na mão", "Shop": "Loja", "Coat": "Casaco", "Zara": "Zara", "Catwalk": "Passarela", "Fashion Bag": "Bolsa de moda", "Girl": "Garota", "Yoghurt": "Iogurte", "Bowl": "Tigela", "Spices": "Especiarias", "Bullit in Space": "Bullit no espaço", "Bottle": "Garrafa", "Chemical": "Químico", "Beach": "Praia", "Sea": "Mar", "Paper": "Papel", "Pencil": "Lápis", "Highlighter": "Marcador", "Calendar": "Calendário", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-HK": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "sk-SK": ["Wooden Guitar": "Drevená gitara", "Chello": "Chello", "Man": "Muž", "Brass Chello": "Mosadz Chello", "Coffee": "Káva", "Stationary": "Stacionárny", "Laptop": "Laptop", "Coffee Brew": "Kávové varenie", "Man painting on a wall": "Muž maľuje na stenu", "Phone": "Telefón", "Bed": "Posteľ", "Dry Leaves": "Suché listy", "Pillow": "Vankúš", "Music": "Hudba", "Speaker": "Reproduktor", "Gold watch": "Zlaté hodinky", "Headphones": "Slúchadlá", "Grey watch": "Sivé hodinky", "Desk watch": "Stolné hodinky", "Bullitt": "Bullitt", "Space": "Priestor", "Earring": "Náušnica", "Tux": "Tux", "Ring": "Prsteň", "Hand": "Ruka", "White Apple Smart Watch": "Biele inteligentné hodinky Apple", "Glasses": "Okuliare", "Garmin Sports Watch": "Športové hodinky Garmin", "Tea": "Čaj", "Wood color watch": "Hodinky vo farbe dreva", "Watch in hand": "Hodinky v ruke", "Shop": "Obchod", "Coat": "Plášť", "Zara": "Zara", "Catwalk": "Móle", "Fashion Bag": "Módna taška", "Girl": "Dievča", "Yoghurt": "Jogurt", "Bowl": "Misa", "Spices": "Korenie", "Bullit in Space": "Bullit vo vesmíre", "Bottle": "Fľaša", "Chemical": "Chemikália", "Beach": "Pláž", "Sea": "More", "Paper": "Papier", "Pencil": "Ceruzka", "Highlighter": "Zvýrazňovač", "Calendar": "Kalendár", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-PT": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "es-ES": ["Wooden Guitar": "Guitarra de madera", "Chello": "Chello", "Man": "Hombre", "Brass Chello": "Chello de latón", "Coffee": "Café", "Stationary": "Estacionario", "Laptop": "Portátil", "Coffee Brew": "Preparación de café", "Man painting on a wall": "Hombre pintando en una pared", "Phone": "Teléfono", "Bed": "Cama", "Dry Leaves": "Hojas secas", "Pillow": "Almohada", "Music": "Música", "Speaker": "Orador", "Gold watch": "Reloj de oro", "Headphones": "Auriculares", "Grey watch": "Reloj gris", "Desk watch": "Reloj de escritorio", "Bullitt": "Bullitt", "Space": "Espacio", "Earring": "Arete", "Tux": "Tux", "Ring": "Anillo", "Hand": "Mano", "White Apple Smart Watch": "Reloj inteligente Apple blanco", "Glasses": "Gafas", "Garmin Sports Watch": "Reloj deportivo Garmin", "Tea": "Té", "Wood color watch": "Reloj color madera", "Watch in hand": "Reloj en mano", "Shop": "Tienda", "Coat": "Abrigo", "Zara": "Zara", "Catwalk": "Pasarela", "Fashion Bag": "Bolso de moda", "Girl": "Muchacha", "Yoghurt": "Yogur", "Bowl": "Tazón", "Spices": "Especias", "Bullit in Space": "Bullit en el espacio", "Bottle": "Botella", "Chemical": "Químico", "Beach": "Playa", "Sea": "Mar", "Paper": "Papel", "Pencil": "Lápiz", "Highlighter": "Iluminador", "Calendar": "Calendario", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "en-DK": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "cs": ["Wooden Guitar": "Dřevěná kytara", "Chello": "Chello", "Man": "Muž", "Brass Chello": "Mosazné Chello", "Coffee": "Káva", "Stationary": "Stacionární", "Laptop": "Notebook", "Coffee Brew": "Vaření kávy", "Man painting on a wall": "Muž malující na zeď", "Phone": "Telefon", "Bed": "Postel", "Dry Leaves": "Suché listí", "Pillow": "Polštář", "Music": "Hudba", "Speaker": "Reproduktor", "Gold watch": "Zlaté hodinky", "Headphones": "Sluchátka", "Grey watch": "Šedé hodinky", "Desk watch": "Stolní hodinky", "Bullitt": "Bullitt", "Space": "Prostor", "Earring": "Náušnice", "Tux": "Smoking", "Ring": "Prsten", "Hand": "Ruka", "White Apple Smart Watch": "Bílé chytré hodinky Apple", "Glasses": "Brýle", "Garmin Sports Watch": "Sportovní hodinky Garmin", "Tea": "Čaj", "Wood color watch": "Hodinky v barvě dřeva", "Watch in hand": "Hodinky v ruce", "Shop": "Obchod", "Coat": "Kabát", "Zara": "Zara", "Catwalk": "Pódium", "Fashion Bag": "Módní taška", "Girl": "Děvče", "Yoghurt": "Jogurt", "Bowl": "Mísa", "Spices": "Koření", "Bullit in Space": "Bullit ve vesmíru", "Bottle": "Láhev", "Chemical": "Chemický", "Beach": "Pláž", "Sea": "Moře", "Paper": "Papír", "Pencil": "Tužka", "Highlighter": "Zvýrazňovač", "Calendar": "Kalendář", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "it-IT": ["Wooden Guitar": "Chitarra in legno", "Chello": "Chello", "Man": "Uomo", "Brass Chello": "Ottone Chello", "Coffee": "Caffè", "Stationary": "Stazionario", "Laptop": "Portatile", "Coffee Brew": "Caffè Brew", "Man painting on a wall": "Uomo che dipinge su un muro", "Phone": "Telefono", "Bed": "Letto", "Dry Leaves": "Foglie secche", "Pillow": "Guanciale", "Music": "Musica", "Speaker": "Altoparlante", "Gold watch": "Orologio d'oro", "Headphones": "Cuffia", "Grey watch": "Orologio grigio", "Desk watch": "Orologio da tavolo", "Bullitt": "Bullitt", "Space": "Spazio", "Earring": "Orecchino", "Tux": "Tux", "Ring": "Anello", "Hand": "Mano", "White Apple Smart Watch": "Orologio intelligente Apple bianco", "Glasses": "Occhiali", "Garmin Sports Watch": "Orologio sportivo Garmin", "Tea": "Tè", "Wood color watch": "Orologio color legno", "Watch in hand": "Orologio alla mano", "Shop": "Negozio", "Coat": "Cappotto", "Zara": "Zara", "Catwalk": "Passerella", "Fashion Bag": "Borsa alla moda", "Girl": "Ragazza", "Yoghurt": "Yogurt", "Bowl": "Ciotola", "Spices": "Spezie", "Bullit in Space": "Bullit nello spazio", "Bottle": "Bottiglia", "Chemical": "Chimico", "Beach": "Spiaggia", "Sea": "Mare", "Paper": "Carta", "Pencil": "Matita", "Highlighter": "Evidenziatore", "Calendar": "Calendario", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "th": ["Wooden Guitar": "กีตาร์ไม้", "Chello": "เชลโล", "Man": "ผู้ชาย", "Brass Chello": "ทองเหลือง Chello", "Coffee": "กาแฟ", "Stationary": "นิ่ง", "Laptop": "แล็ปท็อป", "Coffee Brew": "กาแฟชง", "Man painting on a wall": "ชายวาดภาพบนผนัง", "Phone": "โทรศัพท์", "Bed": "เตียง", "Dry Leaves": "ใบแห้ง", "Pillow": "หมอน", "Music": "ดนตรี", "Speaker": "ลำโพง", "Gold watch": "นาฬิกาทอง", "Headphones": "หู ฟัง", "Grey watch": "นาฬิกาสีเทา", "Desk watch": "นาฬิกาตั้งโต๊ะ", "Bullitt": "บูลลิตต์", "Space": "อวกาศ", "Earring": "ต่างหู", "Tux": "ทักซ์", "Ring": "แหวน", "Hand": "มือ", "White Apple Smart Watch": "Apple สมาร์ทวอทช์สีขาว", "Glasses": "แว่นตา", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "ชา", "Wood color watch": "นาฬิกาสีไม้", "Watch in hand": "นาฬิกาในมือ", "Shop": "ร้าน", "Coat": "หุ้ม", "Zara": "ซาร่า", "Catwalk": "แคทวอล์ค", "Fashion Bag": "กระเป๋าแฟชั่น", "Girl": "เด็กผู้หญิง", "Yoghurt": "นมเปรี้ยว", "Bowl": "ชาม", "Spices": "เครื่องเทศ", "Bullit in Space": "บูลลิตในอวกาศ", "Bottle": "ขวด", "Chemical": "เคมี", "Beach": "หาด", "Sea": "ทะเล", "Paper": "กระดาษ", "Pencil": "ดินสอ", "Highlighter": "ปากกาเน้นข้อความ", "Calendar": "ปฏิทิน", "Bullitt-1": "Bullitt-1 (บูลลิต-1)", "Bullitt-2": "บูลลิต-2"],
        "sv-SE": ["Wooden Guitar": "Trägitarr", "Chello": "Chello", "Man": "Man", "Brass Chello": "Mässing Chello", "Coffee": "Kaffe", "Stationary": "Stationär", "Laptop": "Bärbar dator", "Coffee Brew": "Kaffe Brygga", "Man painting on a wall": "Man målning på en vägg", "Phone": "Telefon", "Bed": "Säng", "Dry Leaves": "Torra löv", "Pillow": "Kudde", "Music": "Musik", "Speaker": "Högtalare", "Gold watch": "Guldfärgad klocka", "Headphones": "Hörlurar", "Grey watch": "Grå klocka", "Desk watch": "Klocka på skrivbordet", "Bullitt": "Bullitt", "Space": "Rymd", "Earring": "Örhänge", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "Vit Apple Smart Watch", "Glasses": "Glasögon", "Garmin Sports Watch": "Garmin sportklocka", "Tea": "Te", "Wood color watch": "Trä färg klocka", "Watch in hand": "Klocka i handen", "Shop": "Butik", "Coat": "Rock", "Zara": "Zara", "Catwalk": "Catwalken", "Fashion Bag": "Mode Väska", "Girl": "Flicka", "Yoghurt": "Yoghurt", "Bowl": "Skål", "Spices": "Kryddor", "Bullit in Space": "Bullit i rymden", "Bottle": "Flaska", "Chemical": "Kemisk", "Beach": "Strand", "Sea": "Hav", "Paper": "Papper", "Pencil": "Blyertspenna", "Highlighter": "Överstrykningspenna", "Calendar": "Kalender", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "da-DK": ["Wooden Guitar": "Træ Guitar", "Chello": "Chello", "Man": "Mand", "Brass Chello": "Messing Chello", "Coffee": "Kaffe", "Stationary": "Stationære", "Laptop": "Bærbar computer", "Coffee Brew": "Kaffe bryg", "Man painting on a wall": "Mand maler på en væg", "Phone": "Telefon", "Bed": "Seng", "Dry Leaves": "Tørre blade", "Pillow": "Pude", "Music": "Musik", "Speaker": "Højttaler", "Gold watch": "Guld ur", "Headphones": "Hovedtelefoner", "Grey watch": "Gråt ur", "Desk watch": "Skrivebordsur", "Bullitt": "Bullitt", "Space": "Rum", "Earring": "Ørering", "Tux": "Tux", "Ring": "Ring", "Hand": "Hånd", "White Apple Smart Watch": "Hvid Apple Smart Watch", "Glasses": "Briller", "Garmin Sports Watch": "Garmin sportsur", "Tea": "Te", "Wood color watch": "Træ farveur", "Watch in hand": "Ur i hånden", "Shop": "Butik", "Coat": "Frakke", "Zara": "Zara", "Catwalk": "Løbebro", "Fashion Bag": "Mode taske", "Girl": "Pige", "Yoghurt": "Yoghurt", "Bowl": "Skål", "Spices": "Krydderier", "Bullit in Space": "Bullit i rummet", "Bottle": "Flaske", "Chemical": "Kemisk", "Beach": "Strand", "Sea": "Hav", "Paper": "Papir", "Pencil": "Blyant", "Highlighter": "Overstregningstusch", "Calendar": "Kalender", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"],
        "pl": ["Wooden Guitar": "Drewniana gitara", "Chello": "Chello powiedział:", "Man": "Mężczyzna", "Brass Chello": "Mosiężne Chello", "Coffee": "Kawa", "Stationary": "Nieruchomy", "Laptop": "Laptop", "Coffee Brew": "Napar kawy", "Man painting on a wall": "Mężczyzna maluje na ścianie", "Phone": "Telefon", "Bed": "Łóżko", "Dry Leaves": "Suche liście", "Pillow": "Poduszka", "Music": "Muzyka", "Speaker": "Głośnik", "Gold watch": "Złoty zegarek", "Headphones": "Słuchawki", "Grey watch": "Szary zegarek", "Desk watch": "Wacht biurkowy", "Bullitt": "Bullitt powiedział:", "Space": "Przestrzeń", "Earring": "Kolczyk", "Tux": "Tux", "Ring": "Pierścień", "Hand": "Ręka", "White Apple Smart Watch": "Biały inteligentny zegarek Apple", "Glasses": "Okulary", "Garmin Sports Watch": "Zegarek sportowy Garmin", "Tea": "Herbata", "Wood color watch": "Zegarek w kolorze drewna", "Watch in hand": "Zegarek w ręku", "Shop": "Sklep", "Coat": "Płaszcz", "Zara": "Zara", "Catwalk": "Wybiegu", "Fashion Bag": "Modna torba", "Girl": "Dziewczyna", "Yoghurt": "Jogurt", "Bowl": "Misa", "Spices": "Przyprawy", "Bullit in Space": "Byk w kosmosie", "Bottle": "Butelka", "Chemical": "Chemiczny", "Beach": "Plaża", "Sea": "Morze", "Paper": "Papier", "Pencil": "Ołówek", "Highlighter": "Zakreślacz", "Calendar": "Kalendarz", "Bullitt-1": "Bullitt-1 powiedział:", "Bullitt-2": "Bullitt-2 powiedział:"],
        "he": ["Wooden Guitar": "גיטרת עץ", "Chello": "צ'לו", "Man": "איש", "Brass Chello": "פליז צ'לו", "Coffee": "קפה", "Stationary": "נייחים", "Laptop": "מחשב נייד", "Coffee Brew": "חליטת קפה", "Man painting on a wall": "איש מצייר על קיר", "Phone": "טלפון", "Bed": "מיטה", "Dry Leaves": "עלים יבשים", "Pillow": "כרית", "Music": "מוזיקה", "Speaker": "רמקול", "Gold watch": "שעון זהב", "Headphones": "אוזניות", "Grey watch": "שעון אפור", "Desk watch": "שעון שולחן", "Bullitt": "בוליט", "Space": "חלל", "Earring": "עגיל", "Tux": "טוקס", "Ring": "טבעת", "Hand": "יד", "White Apple Smart Watch": "שעון חכם לבן של Apple", "Glasses": "משקפיים", "Garmin Sports Watch": "שעון ספורט של Garmin", "Tea": "תה", "Wood color watch": "שעון צבעוני מעץ", "Watch in hand": "שעון ביד", "Shop": "חנות", "Coat": "מעיל", "Zara": "זארה", "Catwalk": "המסלול", "Fashion Bag": "תיק אופנה", "Girl": "ילדה", "Yoghurt": "יוגורט", "Bowl": "קערה", "Spices": "תבלינים", "Bullit in Space": "בוליט בחלל", "Bottle": "בקבוק", "Chemical": "כימי", "Beach": "חוף", "Sea": "ים", "Paper": "נייר", "Pencil": "עיפרון", "Highlighter": "עט סימון", "Calendar": "לוח שנה", "Bullitt-1": "בוליט-1", "Bullitt-2": "בוליט-2"],
        "en-ID": ["Wooden Guitar": "Wooden Guitar", "Chello": "Chello", "Man": "Man", "Brass Chello": "Brass Chello", "Coffee": "Coffee", "Stationary": "Stationary", "Laptop": "Laptop", "Coffee Brew": "Coffee Brew", "Man painting on a wall": "Man painting on a wall", "Phone": "Phone", "Bed": "Bed", "Dry Leaves": "Dry Leaves", "Pillow": "Pillow", "Music": "Music", "Speaker": "Speaker", "Gold watch": "Gold watch", "Headphones": "Headphones", "Grey watch": "Grey watch", "Desk watch": "Desk watch", "Bullitt": "Bullitt", "Space": "Space", "Earring": "Earring", "Tux": "Tux", "Ring": "Ring", "Hand": "Hand", "White Apple Smart Watch": "White Apple Smart Watch", "Glasses": "Glasses", "Garmin Sports Watch": "Garmin Sports Watch", "Tea": "Tea", "Wood color watch": "Wood color watch", "Watch in hand": "Watch in hand", "Shop": "Shop", "Coat": "Coat", "Zara": "Zara", "Catwalk": "Catwalk", "Fashion Bag": "Fashion Bag", "Girl": "Girl", "Yoghurt": "Yoghurt", "Bowl": "Bowl", "Spices": "Spices", "Bullit in Space": "Bullit in Space", "Bottle": "Bottle", "Chemical": "Chemical", "Beach": "Beach", "Sea": "Sea", "Paper": "Paper", "Pencil": "Pencil", "Highlighter": "Highlighter", "Calendar": "Calendar", "Bullitt-1": "Bullitt-1", "Bullitt-2": "Bullitt-2"]
]


def getLocale(resource) {
    def path = resource.getPath();
    if(path.startsWith("/content/experience-fragments")) {
        path =path.replace("/experience-fragments", "")
        def regex = "^((?:[^/]*\\/){4}[^/]*)";
        def pattern = Pattern.compile(regex);
        def matcher = pattern.matcher(path);
        path = matcher.find() ? matcher.group(1) : path
    }
    path = path.replaceAll('/jcr:content.*', "")
    def page = getPage(path)
    if (page == null){
        println """Page is not found: ${path}"""
        return new Locale("en");
    }
    return page.getLanguage();
}

def translate_PARALLAX_SECTION(phrase, locale) {
    def localeString = locale.toString();
    def language = locale.getLanguage();

    if(DICTIONARY_PARALLAX_SECTION.containsKey(localeString) && DICTIONARY_PARALLAX_SECTION[localeString].containsKey(phrase)) {
        return DICTIONARY_PARALLAX_SECTION[localeString][phrase];
    } else if (DICTIONARY_PARALLAX_SECTION.containsKey(language) && DICTIONARY_PARALLAX_SECTION[language].containsKey(phrase)) {
        return DICTIONARY_PARALLAX_SECTION[language][phrase];
    } else {
        return phrase;
    }
}


def handleParallaxSection(homePage) {
    def types = ["chemical-impact","creative-campaigns","death-of-the-double-bass","dhl-boxes","e-commerce-winning","getting-certified","men-jewelry","smartwatches","taking-fashion-home","trending-in-grooming","larry-vs-harry"];
    def resourceType ="dhl/components/animated-content/parallax-section";
    def properties = [
            "bkImgAreaLabel1" : "Wooden Guitar",
            "bkImgAreaLabel2" : "Chello",
            "bkImgAreaLabel3" : "Man",
            "bkImgAreaLabel4" : "Brass Chello",
            "bkImgAreaLabel5" : "Coffee",
            "bkImgAreaLabel6" : "Stationary",
            "bkImgAreaLabel7" : "Laptop",
            "bkImgAreaLabel8" : "Coffee Brew",
            "bkImgAreaLabel9" : "Phone",
            "bkImgAreaLabel10" : "Bed",
            "bkImgAreaLabel11" : "Dry Leaves",
            "bkImgAreaLabel12" : "Pillow",
            "bkImgAreaLabel13" : "Music",
            "bkImgAreaLabel14" : "Speaker",
            "bkImgAreaLabel15" : "Gold watch",
            "bkImgAreaLabel16" : "Headphones",
            "bkImgAreaLabel17" : "Speaker",
            "bkImgAreaLabel18" : "Grey watch",
            "bkImgAreaLabel19" : "Desk watch",
            "bkImgAreaLabel20" : "Earring",
            "bkImgAreaLabel21" : "Tux",
            "bkImgAreaLabel22" : "Ring",
            "bkImgAreaLabel23" : "Hand",
            "bkImgAreaLabel24" : "White Apple Smart Watch",
            "bkImgAreaLabel25" : "Glasses",
            "bkImgAreaLabel26" : "Garmin Sports Watch",
            "bkImgAreaLabel27" : "Tea",
            "bkImgAreaLabel28" : "Wood color watch",
            "bkImgAreaLabel29" : "Watch in hand",
            "bkImgAreaLabel30" : "Shop",
            "bkImgAreaLabel31" : "Coat",
            "bkImgAreaLabel32" : "Zara",
            "bkImgAreaLabel33" : "Catwalk",
            "bkImgAreaLabel34" : "Fashion Bag",
            "bkImgAreaLabel35" : "Girl",
            "bkImgAreaLabel36" : "Yoghurt",
            "bkImgAreaLabel37" : "Bowl",
            "bkImgAreaLabel38" : "Spices",
            "bkImgAreaLabel39" : "Bottle",
            "bkImgAreaLabel40" : "Chemical",
            "bkImgAreaLabel41" : "Beach",
            "bkImgAreaLabel42" : "Sea",
            "bkImgAreaLabel43" : "Paper",
            "bkImgAreaLabel44" : "Pencil",
            "bkImgAreaLabel45" : "Highlighter",
            "bkImgAreaLabel46" : "Calendar",
            "bkImgAreaLabel47" : "Bullitt-1",
            "bkImgAreaLabel48" : "Bullitt in Space",
            "bkImgAreaLabel49" : "Bullitt-2",
    ]
    def typeConditions = types.collect { "node.type = '${it}'" }.join(" OR ");

    def query = """
        SELECT * FROM [nt:unstructured] AS node WHERE ISDESCENDANTNODE([${homePage.getPath()}])
        and (node.[sling:resourceType]='${resourceType}')
        and (${typeConditions})
    """
    sql2Query(query).each( node -> {
        properties.each((key, value) -> {
            def translatedValue = translate_PARALLAX_SECTION(value, getLocale(node));
            println """set ${key}:${translatedValue} to ${node.getPath()}"""
            node.setProperty(key, translatedValue)
        })
    })
}

getHomePages().each( homePage -> {
    handleParallaxSection(homePage);

    if(DRY_RUN) {
        session.refresh(false);
    } else {
        save();
    }
})