package com.dhl.discover.core.models;

import com.adobe.cq.wcm.core.components.models.Image;
import com.day.cq.wcm.api.Page;
import com.day.cq.wcm.api.designer.Style;
import com.dhl.discover.core.injectors.InjectHomeProperty;
import com.dhl.discover.core.models.search.SearchResultEntry;
import com.dhl.discover.core.services.ArticleService;
import com.dhl.discover.core.services.PathUtilService;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.apache.sling.api.SlingHttpServletRequest;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.api.resource.ResourceResolver;
import org.apache.sling.models.annotations.Default;
import org.apache.sling.models.annotations.DefaultInjectionStrategy;
import org.apache.sling.models.annotations.Model;
import org.apache.sling.models.annotations.Required;
import org.apache.sling.models.annotations.injectorspecific.*;

import javax.annotation.PostConstruct;
import javax.inject.Named;
import javax.json.Json;
import javax.json.JsonArrayBuilder;
import javax.json.JsonObject;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import static com.day.cq.wcm.api.commands.WCMCommand.PAGE_TITLE_PARAM;
import static com.dhl.discover.core.services.PageUtilService.CATEGORY_PAGE_DYNAMIC_RESOURCE_TYPE;
import static org.apache.commons.lang3.StringUtils.defaultIfBlank;

@Getter
@Model(adaptables = SlingHttpServletRequest.class, defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL)
@Slf4j
public class ArticleGridV2 {
    @ScriptVariable
    @Required
    private Page currentPage;

    @ScriptVariable
    @Required
    protected Style currentStyle;

    @OSGiService
    @Required
    private ArticleService articleService;

    @OSGiService
    @Required
    private PathUtilService pathUtilService;

    @SlingObject
    @Required
    private ResourceResolver resolver;

    @Self
    private SlingHttpServletRequest request;

    @ValueMapValue
    private String tabSource;

    @ValueMapValue
    private String contentSource;

    @ValueMapValue
    private boolean includeAutogeneratedAllTab;

    @ValueMapValue
    private String title;

    @ChildResource
    private List<TabConfig> tabs;

    @InjectHomeProperty
    @Named("articleGrid-title")
    @Default(values = "Categories")
    private String defaultTitle;

    @InjectHomeProperty
    @Named("articleGrid-allTitle")
    @Default(values = "All")
    private String allCategoryTitle;

    @InjectHomeProperty
    @Named("articleGrid-sortTitle")
    @Default(values = "Sort By")
    private String sortTitle;

    @InjectHomeProperty
    @Named("articleGrid-latestOptionTitle")
    @Default(values = "Latest")
    private String latestOptionTitle;

    @InjectHomeProperty
    @Named("articleGrid-recommendedOptionTitle")
    @Default(values = "Recommended")
    private String recommendedOptionTitle;

    @InjectHomeProperty
    @Named("articleGrid-ShowMoreButtonTitle")
    @Default(values = "Show More")
    private String showMoreButtonTitle;

    @InjectHomeProperty
    @Named("articleGrid-showTags")
    private boolean showTags;

    private boolean enableAssetDelivery;

    private final Map<String, List<Article>> categoryArticleMap = new LinkedHashMap<>();

    @PostConstruct
    private void init() {
        enableAssetDelivery = currentStyle.get("enableAssetDelivery", false);

        if ("customByTags".equals(tabSource)) {
            initTagBasedCategories();
        } else {
            initChildCategories();
        }
    }

    private void initTagBasedCategories() {
        if(tabs == null) {
            return;
        }
        tabs.forEach(tab -> {
            var results = articleService.findArticlesByTag(tab.getTags(), contentSource, request);
            var articles = results.stream()
                    .map(SearchResultEntry::getArticle)
                    .peek(article -> article.initAssetDeliveryProperties(enableAssetDelivery))
                    .collect(Collectors.toList());
            categoryArticleMap.put(tab.getTitle(), articles);
        });
    }

    private void initChildCategories() {
        includeAutogeneratedAllTab = false;
        var allArticles = articleService.getAllArticles(currentPage, request);
        allArticles.forEach(article -> article.initAssetDeliveryProperties(enableAssetDelivery));
        categoryArticleMap.put(allCategoryTitle, allArticles);

        getSubCategories().forEach(category -> {
            var categoryArticles = articleService.getAllArticles(category, request);
            categoryArticles.forEach(article -> article.initAssetDeliveryProperties(enableAssetDelivery));
            var categoryTitle = defaultIfBlank(category.getNavigationTitle(), category.getTitle());
            if (categoryTitle != null) {
                categoryArticleMap.put(categoryTitle, categoryArticles);
            }
        });
    }

    private List<Page> getSubCategories() {
        List<Page> subCategories = new ArrayList<>();
        currentPage.listChildren().forEachRemaining(page -> {
            String template = java.util.Optional.of(page)
                    .map(Page::getContentResource)
                    .map(Resource::getResourceType)
                    .orElse("");
            if (CATEGORY_PAGE_DYNAMIC_RESOURCE_TYPE.equals(template) && !page.isHideInNav()) {
                subCategories.add(page);
            }
        });

        return subCategories;
    }

    public String toJson() {
        JsonArrayBuilder categories = Json.createArrayBuilder();
        categoryArticleMap.forEach((category, articles) -> {
            JsonArrayBuilder articlesJson = Json.createArrayBuilder();
            articles.forEach(article -> {
                var featuredImageModel = article.getFeaturedImageModel();
                JsonObject articleJson = Json.createObjectBuilder()
                        .add(PAGE_TITLE_PARAM, article.getNavTitle())
                        .add("path", article.getPath())
                        .add("description", article.getDescription())
                        .add("pageImage", StringUtils.defaultIfBlank(pathUtilService.map(featuredImageModel.getSrc()), "/etc.clientlibs/dhl/clientlibs/discover/resources/img/articleHeroHomepage-desk.jpg"))
                        .add("imageSrcSet", StringUtils.defaultString(pathUtilService.map(featuredImageModel.getSrcset())))
                        .add("imageSize", "")
                        .add("imageAlt", StringUtils.defaultString(featuredImageModel.getAlt()))
                        .add("createdfriendly", article.getCreatedfriendly())
                        .add("createdMilliseconds", article.getCreatedMilliseconds())
                        .add("author", article.getAuthor())
                        .add("groupTag", article.getGroupTag())
                        .add("tagsToShow", Json.createArrayBuilder(article.getTagsToShow()).build())
                        .add("highlights", Json.createArrayBuilder(article.getHighlights()).build())
                        .build();
                articlesJson.add(articleJson);
            });
            categories.add(Json.createObjectBuilder().add("name", category).add("articles", articlesJson));
        });
        categories.build();

        return Json.createObjectBuilder()
                .add(PAGE_TITLE_PARAM, StringUtils.defaultIfBlank(title, defaultTitle))
                .add("showTags", showTags)
                .add("includeAutogeneratedAllTab", includeAutogeneratedAllTab)
                .add("allCategoryTitle", allCategoryTitle)
                .add("categories", categories)
                .add("showMoreResultsButtonTitle", showMoreButtonTitle)
                .add("recommendedOptionTitle", recommendedOptionTitle)
                .add("latestOptionTitle", latestOptionTitle)
                .add("sortingTitle", sortTitle)
                .build().toString();
    }

    @Model(adaptables = Resource.class, defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL)
    @Getter
    public static class TabConfig {

        @ValueMapValue
        @Default(values = "")
        private String title;

        @ValueMapValue
        private List<String> tags;
    }

    public boolean hasArticles() {
        return categoryArticleMap.values().stream().anyMatch(articles -> !articles.isEmpty());
    }
}
