name: 'Maven Build and Test'
description: 'Runs mvn clean verify and uploads JaCoCo coverage results.'
runs:
  using: "composite"
  steps:
    - name: Build and Test
      shell: bash
      run: mvn clean verify -B
      env:
        # Proxy settings for Maven
        HTTP_PROXY: http://b2b-http.dhl.com:8080
        HTTPS_PROXY: http://b2b-http.dhl.com:8080
        NO_PROXY: "localhost,127.0.0.1,artifactory.dhl.com"

        # Cypress-specific proxy settings
        CYPRESS_PROXY: http://b2b-http.dhl.com:8080
        npm_config_proxy: http://b2b-http.dhl.com:8080
        npm_config_https_proxy: http://b2b-http.dhl.com:8080

        # Additional Cypress environment variables for troubleshooting
        CYPRESS_CACHE_FOLDER: ./node_modules/cypress_cache
        CYPRESS_INSTALL_BINARY: 0 # Set to 0 to skip binary download during npm install, then control it manually
    - name: Upload JaCoCo code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-result
        path: |
          target/site/
          target/jacoco.exec
          target/surefire-reports
