import React, { useRef, useState } from 'react';

import { registerComponent } from '../../react-core';
import { ArticleCard, CategorySelector } from './molecules';
import { ArticleCategory } from '../../types/article';
import { useDisplayArticles, useDisplayedCategories } from './hooks';
import { SortSelect } from '../common/atoms';

import styles from './styles.module.scss';

interface SortOption {
  value: 'recommended' | 'latest';
  label: string;
}

interface ArticleGridProps {
  title: string;
  showMoreResultsButtonTitle: string;
  latestOptionTitle: string,
  recommendedOptionTitle: string,
  sortingTitle: string,
  allCategoryTitle: string,
  categories: ArticleCategory[];
  includeAutogeneratedAllTab: boolean;
  showTags?: boolean;
}

export const ArticleGrid: React.FC<ArticleGridProps> = ({
  title,
  latestOptionTitle,
  recommendedOptionTitle,
  showMoreResultsButtonTitle,
  sortingTitle,
  categories,
  allCategoryTitle,
  includeAutogeneratedAllTab,
  showTags
}) => {
  const selectOptions: SortOption[] = [
    { value: 'recommended', label: recommendedOptionTitle },
    { value: 'latest', label: latestOptionTitle },
  ];

  const articleGridRef = useRef<HTMLDivElement>(null);
  const displayedCategories = useDisplayedCategories(categories, includeAutogeneratedAllTab, allCategoryTitle);
  const [selectedSortOption, setSelectedSortOption] = useState<any>(selectOptions[0]);

  const [selectedCategory, setCategory] = useState(displayedCategories.length 
    ? displayedCategories[0] 
    : { name: '', articles: [], id: 0 });

  const [displayedArticles, showMoreArticles] = useDisplayArticles(
    selectedCategory.articles, 
    selectedSortOption.value, 
    articleGridRef);

  const hasMultipleCategories = displayedCategories.length > 1;

  return (
    <div className={styles.articleGrid}>
      <div className={styles.articleGridHeader}>
        <div className={styles.articleGridHeaderTitle}>{title}</div>
        <SortSelect
          onChange={setSelectedSortOption}
          options={selectOptions}
          sortingTitle={sortingTitle}
        />
      </div>

      {hasMultipleCategories 
        &&<CategorySelector 
          displayedCategories={displayedCategories}
          selectedCategory={selectedCategory}
          onSelectCategory={setCategory}
        />
      }

      <div
        {...(hasMultipleCategories && {
          id: `article-grid-tabpanel-${selectedCategory.id}`,
          tabIndex: 0,
          "aria-labelledby": `article-grid-tab-${selectedCategory.id}`,
          role: "tabpanel",
        })}
        ref={articleGridRef}
        className={styles.articleGridArticles}>
        {displayedArticles.map((article) => (
          <ArticleCard
            article={article}
            key={article.path}
            showTags={showTags}
          />
        ))}
      </div>

      {displayedArticles.length < selectedCategory.articles.length && (
        <button 
          className={styles.articleGridShowMoreButton} 
          onClick={showMoreArticles}>
          {showMoreResultsButtonTitle}
        </button>
      )}
    </div>
  );
};

registerComponent("article-grid", ArticleGrid);
