name: 'Evaluate Artifact Info'
description: 'Extracts Maven artifactId and version from pom.xml.'
outputs:
  artifact-id:
    description: "The Maven artifact ID"
    value: ${{ steps.extract-project-info.outputs.artifact-id }}
  artifact-version:
    description: "The Maven artifact version"
    value: ${{ steps.extract-project-info.outputs.artifact-version }}
runs:
  using: "composite"
  steps:
    - name: Get Artifact Name and Version
      id: extract-project-info
      shell: bash
      run: |
        echo "artifact-id=`mvn help:evaluate -B -Dexpression=project.artifactId -q -DforceStdout`" >> $GITHUB_OUTPUT
        echo "artifact-version=`mvn help:evaluate -B -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_OUTPUT
    - name: Print Artifact Information
      shell: bash
      run: |
        {
          echo "### Outputs"
          echo "| key                 | Value |"
          echo "| ------------------- | ----- |"
          echo "| artifact-id         | ${{ steps.extract-project-info.outputs.artifact-id }} |"
          echo "| artifact-version    | ${{ steps.extract-project-info.outputs.artifact-version }} |"
        } >> $GITHUB_STEP_SUMMARY
